# Windermere Concrete — city data (part 4 of 4): Tier-2 north corridor (Lake/Seminole).
CITIES = {
    "minneola": {
        "name": "Minneola",
        "slug": "minneola",
        "tier": 2,
        "county": "Lake County",
        "state": "FL",
        "zips": ["34715"],
        "population": "18,000+ and accelerating with the Hills of Minneola build-out",
        "distinction": "Clermont&rsquo;s fast-growing neighbor on Lake Minneola, anchored by the Hills of Minneola mega-development and the turnpike interchange",
        "lat": "28.5744",
        "lng": "-81.7462",
        "neighborhoods": [
            "Hills of Minneola", "Ardmore Reserve", "Reserve at Minneola",
            "Quail Valley", "Oak Valley", "Minneola Harbor Hills", "Downtown Minneola",
        ],
        "profile": "Minneola is what happens when a turnpike interchange opens next to hill country: the Hills of Minneola alone is platted for thousands of homes, and Ardmore Reserve and the Reserve sections are already deep into the cycle every new Florida subdivision follows &mdash; builder-minimum driveways that need widening, bare lanais waiting for pool decks, and HOA palettes steering owners toward pavers. What separates Minneola from the flat metro is the grade. Lots here step down real hills toward Lake Minneola, so driveways carry genuine falls, patios need terraced transitions, and runoff moves fast enough to undercut a lazy base. We treat every Minneola lot like the slope it is: falls engineered from the plat, bases compacted in lifts, and edges restrained against the downhill pull that flatland crews never think about.",
        "profile_short": "Minneola &mdash; hill-country growth next to Clermont, led by the Hills of Minneola build-out. Builder-upgrade cycles on real slopes, where falls and base work decide everything.",
        "terrain_note": "Genuine hillside lots step toward Lake Minneola &mdash; driveways and patios carry engineered falls, and fast-moving runoff punishes any base not compacted in disciplined lifts.",
        "landmarks": "Lake Minneola, the Minneola Trailhead of the South Lake Trail, Hills of Minneola town center site, the Florida&rsquo;s Turnpike interchange",
        "demand_note": "Driveway widening and paver conversions across the Hills build-out, slope-corrected patios, and lakefront pool-deck work",
        "review_note": "City of Minneola permitting; the Hills of Minneola and newer subdivisions run HOA design review.",
    },
    "groveland": {
        "name": "Groveland",
        "slug": "groveland",
        "tier": 2,
        "county": "Lake County",
        "state": "FL",
        "zips": ["34736"],
        "population": "25,000+ and among Lake County&rsquo;s fastest growers",
        "distinction": "The &ldquo;City with Natural Charm&rdquo; on the Green Swamp&rsquo;s eastern edge &mdash; lakes, conservation land, and a wave of new master-planned growth",
        "lat": "28.5581",
        "lng": "-81.8512",
        "neighborhoods": [
            "Trilogy Orlando", "Waterside Pointe", "Cherry Lake Oaks", "Groveland Farms area",
            "Eagle Pointe", "Cascades of Groveland", "Downtown Groveland", "Villa City area",
        ],
        "profile": "Groveland pairs a small historic core with two very different growth engines. Trilogy Orlando &mdash; the gated 55+ resort community &mdash; generates constant, quality-sensitive hardscape: paver courtyards, extended lanais, golf-cart pads, and pool surrounds for owners who are home all day and notice everything. Waterside Pointe and the Clermont Chain access communities add wakeboard-lake energy: boat pads, lakeside patios, and drives built for tow vehicles. Around them both, new subdivisions keep pushing west toward the Green Swamp, where high water tables and organic soils make subgrade probing non-negotiable &mdash; the first question on any Groveland job is what the ground under it actually is. For a crew that takes base engineering seriously, Groveland is honest, steady work in a market most Orlando contractors still drive past.",
        "profile_short": "Groveland &mdash; Trilogy&rsquo;s 55+ resort community, Clermont Chain lake access, and Green Swamp-edge subdivisions. Quality-sensitive paver work and soils that demand real subgrade probing.",
        "terrain_note": "The Green Swamp&rsquo;s eastern edge raises water tables and hides organic pockets &mdash; we probe every subgrade before pricing, because muck under a slab is a guaranteed callback.",
        "landmarks": "Lake David Park, Trilogy Orlando&rsquo;s Magnolia House, the Clermont Chain access lakes, downtown Groveland&rsquo;s murals, the Green Swamp conservation edge",
        "demand_note": "Paver courtyards and lanai extensions in Trilogy, boat pads and lakeside patios at Waterside Pointe, and probe-first driveway work in the newer subdivisions",
        "review_note": "City of Groveland permitting; Trilogy and the gated communities run HOA design review.",
    },
    "oviedo": {
        "name": "Oviedo",
        "slug": "oviedo",
        "tier": 2,
        "county": "Seminole County",
        "state": "FL",
        "zips": ["32765", "32766"],
        "population": "42,000+ city residents",
        "distinction": "Seminole County&rsquo;s family-suburb standard-bearer &mdash; top-rated schools, the Oviedo on the Park district, and the famous downtown chickens",
        "lat": "28.6700",
        "lng": "-81.2081",
        "neighborhoods": [
            "Alafaya Woods", "Twin Rivers", "Live Oak Reserve", "Sanctuary",
            "Kingsbridge East", "Remington Park", "Black Hammock area",
            "Oviedo on the Park district", "Carillon",
        ],
        "profile": "Oviedo&rsquo;s housing stock tells you exactly what it needs: wave after wave of 1980s&ndash;2000s family subdivisions &mdash; Alafaya Woods, Twin Rivers, Kingsbridge East &mdash; whose original builder driveways are now twenty-five to forty years old and showing it. This is replacement-cycle country: tear out the spalled, patched slab, rebuild the base, and pour or pave a driveway that matches a house the owners have been upgrading for a decade. Live Oak Reserve, Sanctuary, and the newer east-side communities add HOA-reviewed paver and pool-deck work, while the Black Hammock&rsquo;s rural lots near Lake Jesup bring long drives and pole-barn pads. Oviedo homeowners research before they hire &mdash; the school-district crowd reads reviews and compares line items &mdash; which suits a company that publishes its pricing and puts every proposal in writing.",
        "profile_short": "Oviedo &mdash; Seminole&rsquo;s family suburb. 1980s&ndash;2000s subdivisions deep in the driveway replacement cycle, HOA-reviewed newer communities, and rural Black Hammock lots near Lake Jesup.",
        "terrain_note": "Closer to Lake Jesup and the Econ basin, water tables rise and soils turn organic &mdash; east-side and Black Hammock jobs get probed and elevation-checked before any base goes in.",
        "landmarks": "Oviedo on the Park, the downtown chickens, Lukas Nursery, the Cross Seminole Trail, Black Hammock on Lake Jesup",
        "demand_note": "Replacement-cycle driveways across the 1980s&ndash;2000s subdivisions, HOA-reviewed paver upgrades in the newer east side, and rural pads in the Black Hammock",
        "review_note": "City of Oviedo or Seminole County permitting by section; HOA review in the newer master-planned communities.",
    },
    "lake-mary": {
        "name": "Lake Mary",
        "slug": "lake-mary",
        "tier": 2,
        "county": "Seminole County",
        "state": "FL",
        "zips": ["32746"],
        "population": "18,000+ city · anchor of Seminole&rsquo;s corporate corridor",
        "distinction": "The I-4 corporate corridor&rsquo;s executive address &mdash; Heathrow, Timacuan, and consistently ranked among Florida&rsquo;s best places to live",
        "lat": "28.7589",
        "lng": "-81.3178",
        "neighborhoods": [
            "Heathrow", "Timacuan", "Magnolia Plantation", "Cardinal Oaks Cove",
            "Huntington Pointe", "Chase Groves", "Lake Mary Woods",
            "Cherry Ridge", "Colonial TownPark district",
        ],
        "profile": "Lake Mary is executive Seminole: guard-gated Heathrow with its country-club streets, Timacuan&rsquo;s golf-course lots, Magnolia Plantation&rsquo;s estate parcels &mdash; a city where the driveway meets the same standard as the landscaping crew that edges it weekly. The work here skews premium and reviewed: paver motor courts and circular drives that pass HOA architectural committees, travertine and marble-paver pool surrounds behind the gates, and outdoor-living terraces built to host. The 1980s&ndash;90s sections outside the gates &mdash; Chase Groves, Lake Mary Woods &mdash; run the familiar replacement cycle at a higher finish expectation than the metro norm. Buyers here compare craftsmanship, not just price; a published Craft Code and a written warranty read exactly the way this market hires.",
        "profile_short": "Lake Mary &mdash; Heathrow, Timacuan, and Seminole&rsquo;s executive corridor. HOA-reviewed motor courts, travertine pool surrounds, and premium replacement-cycle work outside the gates.",
        "terrain_note": "Rolling, oak-canopied lots mix sand with clay lenses &mdash; and gated-community root protection means excavation plans that work around specimen trees, not through them.",
        "landmarks": "Heathrow&rsquo;s gates, Timacuan Golf Club, Colonial TownPark, the Seminole Wekiva Trail, Central Park on Lake Mary Boulevard",
        "demand_note": "Paver and travertine motor courts behind the gates, HOA-reviewed pool surrounds, and premium driveway replacements in the 1980s&ndash;90s sections",
        "review_note": "City of Lake Mary permitting; Heathrow, Timacuan, and most gated communities run ARC review on visible hardscape.",
    },
    "sanford": {
        "name": "Sanford",
        "slug": "sanford",
        "tier": 2,
        "county": "Seminole County",
        "state": "FL",
        "zips": ["32771", "32773"],
        "population": "65,000+ city residents",
        "distinction": "The historic port city on Lake Monroe &mdash; a brick-street downtown, the RiverWalk, and Seminole&rsquo;s county seat",
        "lat": "28.8029",
        "lng": "-81.2695",
        "neighborhoods": [
            "Historic Sanford Residential District", "Lake Forest", "Preserve at Astor Farms",
            "Mayfair", "Celery Estates", "Riverview area", "Sanford Farms",
            "Retreat at Twin Lakes", "Wynwood",
        ],
        "profile": "Sanford has spent two decades restoring itself into one of Central Florida&rsquo;s favorite historic downtowns, and its hardscape market follows that arc. In the Historic Residential District, century-old homes on brick streets need ribbon drives, walkways, and porch aprons that respect the district&rsquo;s character &mdash; work reviewed for compatibility, not just code. Around the edges, Lake Forest and Preserve at Astor Farms bring gated, ARC-reviewed paver and pool-deck work, while the Celery Estates and 32773 subdivisions carry the standard replacement cycle on 1990s&ndash;2000s stock. Lake Monroe adds the waterfront variable: the closer to the RiverWalk and the St. Johns basin, the higher the water table and the more the base and elevation matter. Sanford rewards contractors who can shift registers &mdash; historic restraint downtown, gated-community polish at Lake Forest &mdash; and we built the Craft Code to hold both.",
        "profile_short": "Sanford &mdash; Lake Monroe&rsquo;s historic port city. District-sensitive ribbon drives and walks downtown, gated ARC work at Lake Forest, and replacement-cycle subdivisions south of town.",
        "terrain_note": "The St. Johns / Lake Monroe basin raises water tables near downtown and the RiverWalk &mdash; base elevation and drainage falls get designed against wet-season water, lot by lot.",
        "landmarks": "The Sanford RiverWalk on Lake Monroe, Historic Downtown&rsquo;s First Street, the Central Florida Zoo, Fort Mellon Park, the Auto Train terminal",
        "demand_note": "Historic-district ribbon drives and walkways, gated paver and pool-deck work at Lake Forest and Astor Farms, and replacement-cycle driveways in the southern subdivisions",
        "review_note": "City of Sanford permitting; the Historic District reviews visible hardscape for compatibility, and the gated communities add ARC review.",
    },
    "altamonte-springs": {
        "name": "Altamonte Springs",
        "slug": "altamonte-springs",
        "tier": 2,
        "county": "Seminole County",
        "state": "FL",
        "zips": ["32701", "32714"],
        "population": "46,000+ city residents",
        "distinction": "South Seminole&rsquo;s crossroads city &mdash; Cranes Roost Park, Uptown Altamonte, and mature neighborhoods on the Little Wekiva basin",
        "lat": "28.6614",
        "lng": "-81.3656",
        "neighborhoods": [
            "Spring Oaks", "Sanlando Springs", "Country Creek", "Barclay Woods",
            "Spring Valley area", "Oak Harbour", "Lake Orienta shores",
            "Altamonte Land Hotel district", "The Springs (adjacent)",
        ],
        "profile": "Altamonte Springs is mature suburbia doing what mature suburbia does: replacing the concrete it poured forty years ago. Spring Oaks, Sanlando Springs, Barclay Woods, and the neighborhoods around Lake Orienta were largely built out by the 1980s, which means original driveways, walks, and patio slabs at or past the end of their service life &mdash; cracked, root-heaved, patched, and ready for honest tear-out and rebuild. The Little Wekiva basin threads through the city&rsquo;s west side, raising water tables and adding organic soil pockets that make subgrade probing worth every minute. Oak Harbour and the lakefront condominium communities add association-managed walkway, pool-deck, and common-area flatwork &mdash; board-reviewed, scheduled, and documented. It is straightforward, high-volume replacement country ten minutes up I-4 from our home base, and we treat every one of those forty-year-old slabs as a chance to build the next forty.",
        "profile_short": "Altamonte Springs &mdash; built-out 1970s&ndash;80s suburbia in full replacement cycle. Root-heaved drives and walks around Lake Orienta and the Little Wekiva basin, plus association flatwork at the lakefront communities.",
        "terrain_note": "The Little Wekiva basin raises water tables on the west side, and 1970s-era subdivisions hide roots and patched utilities under original slabs &mdash; probe first, then price.",
        "landmarks": "Cranes Roost Park, Uptown Altamonte, the Altamonte Mall, Lake Orienta, the Little Wekiva River corridor",
        "demand_note": "Replacement-cycle driveways and walkways across the 1970s&ndash;80s stock, root-heave corrections, and association-reviewed common-area flatwork",
        "review_note": "City of Altamonte Springs permitting; condominium and lakefront associations review common-area and visible work.",
    },
}
