# Windermere Concrete — city data (part 2 of 4): Tier-1 Lake County hills + Orlando core.
CITIES = {
    "montverde": {
        "name": "Montverde",
        "slug": "montverde",
        "tier": 1,
        "county": "Lake County",
        "state": "FL",
        "zips": ["34756"],
        "population": "1,900+ in town · several thousand across the CR-455 corridor",
        "distinction": "A hilltop town over Lake Apopka&rsquo;s west shore, home to Bella Collina&rsquo;s Tuscan-style estate community and Montverde Academy",
        "lat": "28.6003",
        "lng": "-81.6742",
        "neighborhoods": [
            "Bella Collina", "Historic Montverde", "Lake Florence area", "CR-455 corridor",
            "Fosgate Road estates", "Porter Road lots", "Ferndale (adjacent)",
        ],
        "profile": "Montverde stacks two extremes onto one ridge. The town itself is old Lake County &mdash; a quiet grid above Lake Apopka where families hold acre lots for generations and a new driveway is a once-in-thirty-years decision. Bella Collina is the other extreme: a Tuscan-styled golf and lake community where motor courts run to hand-laid stone, pool terraces overlook Lake Siena, and the property owners&rsquo; association reviews hardscape with the same rigor as the architecture. Both extremes reward the same discipline. The ridge&rsquo;s rolling elevation &mdash; rare in Florida &mdash; means real slopes, real runoff velocity, and retaining transitions that flatland crews misjudge; driveways here need engineered falls and, sometimes, steps and terracing that most of the Orlando market never encounters. We price Montverde with our eyes open, walk every slope in person, and detail the drawings Bella Collina&rsquo;s review board expects.",
        "profile_short": "Montverde &mdash; hilltop Lake County town anchored by Bella Collina&rsquo;s estate community and Montverde Academy. Real elevation, estate-grade stone and paver work, and POA design review.",
        "terrain_note": "The Lake Apopka ridge brings genuine slopes and clay-streaked soils unusual for Central Florida &mdash; runoff moves fast here, so falls, swales, and step transitions have to be engineered, not eyeballed.",
        "landmarks": "Montverde Academy, Bella Collina&rsquo;s clubhouse hill, Lake Apopka overlooks on CR-455, Lake Florence, Kirk Park",
        "demand_note": "Estate motor courts and stone terraces in Bella Collina; generational driveway replacements and slope-corrected flatwork in town",
        "review_note": "Town of Montverde / Lake County permitting; Bella Collina&rsquo;s POA runs full design review on hardscape.",
    },
    "clermont": {
        "name": "Clermont",
        "slug": "clermont",
        "tier": 1,
        "county": "Lake County",
        "state": "FL",
        "zips": ["34711", "34714", "34715"],
        "population": "45,000+ city · far more across greater south Lake County",
        "distinction": "The &ldquo;Choice of Champions&rdquo; &mdash; hill country on the Clermont Chain of Lakes, marked by the Citrus Tower and a national-caliber triathlon scene",
        "lat": "28.5494",
        "lng": "-81.7729",
        "neighborhoods": [
            "Kings Ridge", "Summit Greens", "Legends", "Lost Lake", "Palisades",
            "Johns Lake Landing", "Greater Hills", "Highland Ranch", "Waterbrooke",
            "Serenoa", "Hartwood Landing", "Verde Park", "Osprey Pointe", "Crestview",
        ],
        "profile": "Clermont is where Central Florida finally gets hills, and the hills change the job. Driveways off Hancock Road or in Palisades drop real elevation between street and garage; a slab poured flat-lander style ponds at the door or washes its own base out in an August storm. The city splits into three distinct markets: the 55+ golf communities &mdash; Kings Ridge, Summit Greens, Legends &mdash; where owners invest steadily in paver drives, screened-lanai extensions, and low-maintenance surfaces; the US-27 growth corridor south toward Four Corners, full of 2000s-era homes hitting their first driveway replacement cycle; and the newer master-planned sections around Johns Lake and Wellness Way, where builder concrete meets the same upgrade wave as west Orange. Add the Clermont Chain&rsquo;s waterfront lots and the constant churn of the triathlon-and-trail crowd resurfacing patios and pool decks, and south Lake is a full-spectrum hardscape market that rewards a crew comfortable working on grade.",
        "profile_short": "Clermont &mdash; hill-country city on the Clermont Chain of Lakes. 55+ golf communities, a US-27 replacement-cycle corridor, and new master-planned growth &mdash; all of it on real slopes that punish flatland shortcuts.",
        "terrain_note": "South Lake&rsquo;s sand-over-clay hills shed stormwater fast &mdash; driveways and patios need engineered falls, and slabs on cut-and-fill lots need bases compacted against differential settlement.",
        "landmarks": "The Citrus Tower, Waterfront Park on Lake Minneola, the South Lake Trail, the Clermont Chain of Lakes, the National Training Center",
        "demand_note": "Paver drives and lanai extensions in the 55+ communities, first-cycle driveway replacements along US-27, and slope-corrected new work around Wellness Way",
        "review_note": "City of Clermont or Lake County permitting depending on the section; HOA review in the golf and master-planned communities.",
    },
    "orlando": {
        "name": "Orlando",
        "slug": "orlando",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32804", "32806", "32812", "32814", "32819", "32835", "32839"],
        "population": "320,000+ city · 2.7 million metro",
        "distinction": "Central Florida&rsquo;s anchor city &mdash; from College Park&rsquo;s brick streets to Baldwin Park&rsquo;s new urbanism and the MetroWest golf corridor",
        "lat": "28.5384",
        "lng": "-81.3789",
        "neighborhoods": [
            "College Park", "Baldwin Park", "Audubon Park", "Delaney Park", "SoDo",
            "Thornton Park", "Colonialtown North", "Dover Shores", "Conway",
            "MetroWest", "Millenia", "Lake Como", "Rowena Gardens", "Orwin Manor",
        ],
        "profile": "We work Orlando selectively &mdash; the neighborhoods where craftsmanship is the buying criterion, not the lowest bid. College Park, Delaney Park, and Audubon Park carry pre-war bungalows on brick streets, where a driveway is two ribbons of concrete under a live oak and the right answer respects the street&rsquo;s character; these blocks generate constant walkway, ribbon-drive, and porch-apron work that big-volume outfits handle badly. Baldwin Park&rsquo;s new-urbanist code produces alley-loaded garages, courtyard patios, and strict material standards closer to an ARC than a typical HOA. To the southwest, MetroWest and the Millenia corridor run on golf-community townhomes and 1990s single-family stock now cycling through driveway and pool-deck replacement. And across Conway and Dover Shores, mid-century block homes on the lake chain want honest tear-out-and-repour work with drainage that finally behaves. It is the widest range of any market we serve, and the Craft Code&rsquo;s forty-eight checkpoints apply on every one of them.",
        "profile_short": "Orlando &mdash; served selectively: College Park and Delaney Park bungalow blocks, Baldwin Park&rsquo;s code-governed new urbanism, MetroWest&rsquo;s golf corridor, and Conway&rsquo;s mid-century lake neighborhoods.",
        "terrain_note": "Older Orlando neighborhoods hide clay lenses, buried debris, and mature root systems under original slabs &mdash; tear-outs get probed and re-based, because pouring over an unknown is how sixty-year-old problems become new ones.",
        "landmarks": "Lake Eola, Dubsdread Golf Course, the Packing District, Leu Gardens, Baldwin Park&rsquo;s New Broad Street, the Mall at Millenia",
        "demand_note": "Ribbon drives and walkways in the bungalow districts, code-compliant hardscape in Baldwin Park, and replacement-cycle driveways and pool decks in MetroWest and Conway",
        "review_note": "City of Orlando permitting; Baldwin Park and several districts enforce design codes on visible hardscape.",
    },
    "winter-park": {
        "name": "Winter Park",
        "slug": "winter-park",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32789", "32792"],
        "population": "30,000+ city residents",
        "distinction": "Central Florida&rsquo;s old-money address &mdash; brick streets, the Winter Park Chain of Lakes, Rollins College, and Park Avenue",
        "lat": "28.5999",
        "lng": "-81.3392",
        "neighborhoods": [
            "Olde Winter Park", "The Vias", "Windsong", "Kenilworth Shores",
            "Orwin Manor", "College Quarter", "Hannibal Square", "Winter Park Pines",
            "Lake Killarney area", "Timber Trail", "Sylvan Lake area", "Georgee&rsquo;s Landing",
        ],
        "profile": "Winter Park is the most exacting market in Central Florida, and we treat it that way. On the brick streets of Olde Winter Park and the Vias, hardscape sits inches from history: circular drives in clay brick or tumbled pavers, bluestone-look entries, and motor courts that must defer to homes a century old. The city&rsquo;s canopy of protected oaks and camphors complicates every excavation &mdash; roots are worked around, not through &mdash; and the Winter Park Chain raises the water table on every lakefront street. In Windsong and the newer enclaves, ARC standards govern materials and colors outright. Even in Winter Park Pines and the 32792 blocks, where mid-century ranches cycle through driveway replacements, buyers expect finish quality a cut above the metro norm because resale here rewards it. This is a city where a paver joint out of line gets noticed from the sidewalk. We line them up.",
        "profile_short": "Winter Park &mdash; brick streets, protected oak canopy, and the Chain of Lakes. Clay-brick circular drives, estate motor courts, and finish standards the resale market actually pays for.",
        "terrain_note": "Lakefront streets on the Winter Park Chain carry a high water table and protected root zones &mdash; excavation, base depth, and drainage get engineered around both, per city tree ordinance.",
        "landmarks": "Park Avenue, Rollins College, the Winter Park Chain of Lakes, Mead Botanical Garden, Casa Feliz, the brick streets themselves",
        "demand_note": "Clay-brick and paver circular drives in Olde Winter Park, ARC-governed work in Windsong, and premium replacement-cycle driveways in the Pines",
        "review_note": "City of Winter Park permitting with an active tree-protection ordinance; Windsong and several enclaves add ARC review.",
    },
    "maitland": {
        "name": "Maitland",
        "slug": "maitland",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32751"],
        "population": "20,000+ city residents",
        "distinction": "The oak-shaded lake city between Winter Park and Altamonte &mdash; six lakes, the historic Maitland Art Center, and some of the metro&rsquo;s most stable neighborhoods",
        "lat": "28.6278",
        "lng": "-81.3631",
        "neighborhoods": [
            "Dommerich Estates", "Dommerich Hills", "Maitland Shores", "Lake Sybelia area",
            "Druid Hills", "Greenwood Gardens", "Maitland Club", "Lake Catherine Shores",
            "Minnehaha Shores", "Country Lane Estates",
        ],
        "profile": "Maitland is a settled city, and settled cities generate a particular kind of hardscape work: the second or third driveway a house has ever had, done by owners who plan to stay. Around Lake Sybelia, Lake Minnehaha, and the Dommerich neighborhoods, 1950s&ndash;70s ranches and colonials sit under a canopy that predates them &mdash; which means root-heaved walks, original slabs past their service life, and owners who want replacements engineered around trees they refuse to lose. The lakes push the water table up on the shore streets, so drainage and base depth are designed, not assumed. Closer to US-17-92 and the Maitland City Centre redevelopment, townhome and infill construction adds courtyard patios and compact paver drives. It is unglamorous, precise work for owners who check references and keep contractors for decades &mdash; exactly the relationship we build for.",
        "profile_short": "Maitland &mdash; six-lake city of stable, oak-canopied neighborhoods. Second-generation driveway replacements, root-aware walkway rebuilds, and lakefront drainage done properly.",
        "terrain_note": "Lakefront streets carry a high seasonal water table and mature root systems &mdash; replacements here are engineered around both, with base depth and falls set to the lot, not to a formula.",
        "landmarks": "Lake Lily Park, the Maitland Art Center, the Enzian Theater, RDV Sportsplex, the Maitland Chain of Lakes",
        "demand_note": "Full driveway replacements under mature canopy, root-aware walkway rebuilds, and lakefront patio and pool-deck work",
        "review_note": "City of Maitland permitting; tree protection applies broadly, and the lakefront overlay districts watch drainage closely.",
    },
    "belle-isle": {
        "name": "Belle Isle",
        "slug": "belle-isle",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32809", "32812"],
        "population": "7,000+ city residents",
        "distinction": "A small city wrapped around the Lake Conway chain &mdash; ski-lake water, mid-century streets, and a five-minute run to the airport",
        "lat": "28.4586",
        "lng": "-81.3592",
        "neighborhoods": [
            "Lake Conway Estates", "Wind Harbor", "Nela Isle", "Conway Acres",
            "Venetian Gardens area", "Seminole Landing", "Swann Beach area",
            "Perkins Road corridor", "Trentwood",
        ],
        "profile": "Belle Isle exists because of water: the city wraps the Lake Conway chain, and most of its streets either touch the lake or look at it. The housing stock is largely 1960s&ndash;80s ranch homes on generous lots &mdash; original driveways now sixty years old, boat pads that were never engineered for the trucks that use them, and backyard slabs that predate the pools they now border. That profile makes Belle Isle a replacement market: tear out the tired slab, rebuild the base in lift-compacted rock, and pour or pave a surface that handles a tow vehicle and a Florida storm. Lakefront lots need particular care &mdash; falls that carry runoff away from the seawall side, and surfaces that shrug off constant wet foot traffic from the ski-and-wakeboard life. With almost no dedicated hardscape competition inside the city, most owners have been hiring from Orlando at large; a crew that actually knows Conway water is the differentiator.",
        "profile_short": "Belle Isle &mdash; the Lake Conway chain&rsquo;s city of mid-century lakefront ranches. Sixty-year-old driveways, boat pads, and pool surrounds in full replacement cycle, with almost no local competition.",
        "terrain_note": "Conway chain lots pair sugar sand with a lake-fed water table &mdash; boat pads and drives get thicker sections and lift-compacted bases so tow vehicles don&rsquo;t print ruts into them.",
        "landmarks": "The Lake Conway chain, Venetian Gardens Park, Cornerstone Charter Academy, the Perkins Road corridor, Warren Park",
        "demand_note": "Driveway replacements on mid-century lots, engineered boat and trailer pads, and lakefront pool-deck rebuilds",
        "review_note": "City of Belle Isle permitting; lakefront work respects the Conway chain&rsquo;s drainage and seawall setbacks.",
    },
}
