# Windermere Concrete — city data (part 3 of 4): Tier-2 south corridor (Osceola/Polk edges).
CITIES = {
    "lake-nona": {
        "name": "Lake Nona",
        "slug": "lake-nona",
        "tier": 2,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32827", "32832"],
        "population": "30,000+ across the Lake Nona planned area",
        "distinction": "Orlando&rsquo;s Medical City &mdash; a design-forward planned district anchored by the USTA National Campus and Lake Nona Town Center",
        "lat": "28.3672",
        "lng": "-81.2812",
        "neighborhoods": [
            "Laureate Park", "Lake Nona Golf &amp; Country Club", "VillageWalk",
            "Northlake Park", "Eagle Creek", "Storey Park", "Randal Park",
            "Isles of Athena", "Somerset Park",
        ],
        "profile": "Lake Nona was master-planned around design, and its homeowners carry that expectation straight into hardscape. Laureate Park&rsquo;s modern architecture calls for large-format pavers, clean-lined courtyard patios, and monolithic slabs with tight, deliberate jointing &mdash; surfaces that photograph like the houses do. Lake Nona Golf &amp; Country Club and Eagle Creek push the estate end: motor courts, summer-kitchen terraces, and pool surrounds vetted by design review. And Storey Park, Randal Park, and the 32832 corridor deliver the familiar new-Florida cycle of builder-minimum driveways ready for widening and paver conversion. The district&rsquo;s HOAs publish real design standards, so material, color, and layout choices get documented and approved before install. Modern lines are less forgiving than rustic ones &mdash; a wavering border reads instantly against minimalist architecture &mdash; which is exactly the kind of tolerance our forty-eight-checkpoint process was written to hold.",
        "profile_short": "Lake Nona &mdash; Orlando&rsquo;s design-forward Medical City district. Modern large-format paver work in Laureate Park, estate courts at the Golf &amp; Country Club, and builder-upgrade cycles in Storey Park and Randal Park.",
        "terrain_note": "Flat, engineered subdivisions with strict drainage plans &mdash; new surfaces must hold the plat&rsquo;s swale flows, and modern large-format materials demand dead-flat screeded beds.",
        "landmarks": "Lake Nona Town Center, the USTA National Campus, Boxi Park, Medical City, the Lake Nona Wave Hotel",
        "demand_note": "Large-format modern paver patios and drives in Laureate Park, estate motor courts in the Club, and driveway widening across the newer villages",
        "review_note": "City of Orlando permitting; Lake Nona HOAs publish explicit design standards for visible hardscape.",
    },
    "celebration": {
        "name": "Celebration",
        "slug": "celebration",
        "tier": 2,
        "county": "Osceola County",
        "state": "FL",
        "zips": ["34747"],
        "population": "11,000+ residents",
        "distinction": "The town Disney built &mdash; a new-urbanist landmark where the pattern book governs everything visible from the street",
        "lat": "28.3253",
        "lng": "-81.5410",
        "neighborhoods": [
            "Main Village", "North Village", "South Village", "East Village",
            "West Village", "Artisan Park", "Island Village", "Aquila Reserve",
        ],
        "profile": "Celebration is the strictest design environment in Central Florida, and everyone who works here knows it. The town&rsquo;s pattern book &mdash; written when Disney master-planned the community &mdash; governs driveway materials, apron details, walkway widths, and even how hardscape meets the picket line. Homes are alley-loaded in much of the Main Village, which puts real wear on rear lanes, garage aprons, and courtyard pads; the climate does the rest, and much of Celebration&rsquo;s original 1990s concrete is now cycling through replacement. The correct approach is documentary: photograph existing conditions, match the specified materials and dimensions, clear the review, and install to the approved drawing. Freelancing a border or upgrading a texture without approval is how owners end up redoing brand-new work. We build inside the lines &mdash; and inside Celebration, the lines are the product.",
        "profile_short": "Celebration &mdash; Disney&rsquo;s new-urbanist town, governed by a pattern book. Original 1990s concrete in replacement cycle; alley aprons, courtyard pads, and walkways built exactly to the approved drawing.",
        "terrain_note": "Low-lying former wetland edges mean engineered drainage throughout &mdash; every replacement must hold original design flows, and organic pockets near preserve edges call for subgrade probing.",
        "landmarks": "Downtown Celebration and Market Street, Celebration Golf Club, the Chain of Lakes trails, Bohemian Hotel Celebration",
        "demand_note": "Pattern-book driveway and apron replacements, alley-loaded garage pads, and courtyard patio rebuilds on 1990s-era stock",
        "review_note": "Osceola County permitting; Celebration&rsquo;s review process governs materials and dimensions of visible hardscape.",
    },
    "kissimmee": {
        "name": "Kissimmee",
        "slug": "kissimmee",
        "tier": 2,
        "county": "Osceola County",
        "state": "FL",
        "zips": ["34741", "34743", "34744", "34746", "34747"],
        "population": "80,000+ city · far larger urbanized area",
        "distinction": "Osceola&rsquo;s county seat on Lake Tohopekaliga &mdash; a historic lakefront downtown ringed by resort corridors and fast-growing residential belts",
        "lat": "28.2919",
        "lng": "-81.4076",
        "neighborhoods": [
            "Bellalago", "Tapestry", "Tohoqua", "Storey Lake", "The Oaks",
            "Remington", "Kissimmee Bay", "Brighton Lakes", "Shingle Creek area",
            "Historic Downtown Kissimmee",
        ],
        "profile": "Kissimmee runs wider than its postcard: beyond the resort strips, it is a working residential city with three distinct hardscape lanes. The established neighborhoods around downtown and the Lake Toho shore &mdash; some dating to the cattle-town era &mdash; carry original driveways and walks decades past their design life, prime for honest tear-out and replacement. The master-planned belt &mdash; Bellalago, Tohoqua, Tapestry, Storey Lake &mdash; delivers the builder-upgrade cycle: paver conversions, pool decks behind new pools, and HOA-reviewed patios. And the short-term-rental corridors along US-192 and toward 34747 add a commercial-adjacent market of pool-deck refreshes and durable, high-traffic surfaces between guest turnovers. Lake Toho&rsquo;s floodplain geometry makes drainage the first question on any lakeside job, and Osceola&rsquo;s sandy flats reward the same lift-compacted bases we build everywhere else.",
        "profile_short": "Kissimmee &mdash; Osceola&rsquo;s seat on Lake Toho. Aging downtown-era driveways, a master-planned upgrade belt (Bellalago, Tohoqua, Storey Lake), and high-traffic rental-corridor pool decks.",
        "terrain_note": "Lakeside sections sit near Toho&rsquo;s floodplain &mdash; drainage falls and base elevation are checked against real storm behavior, not just the plat.",
        "landmarks": "Lake Toho lakefront park, Historic Downtown Kissimmee, Old Town on US-192, Gaylord Palms, Shingle Creek Regional Trail",
        "demand_note": "Tear-out replacements in the established grid, paver and pool-deck upgrades in the master-planned belt, and durable rental-corridor surfaces",
        "review_note": "City of Kissimmee or Osceola County permitting by section; HOA review across the master-planned communities.",
    },
    "st-cloud": {
        "name": "St. Cloud",
        "slug": "st-cloud",
        "tier": 2,
        "county": "Osceola County",
        "state": "FL",
        "zips": ["34769", "34771", "34772", "34773"],
        "population": "60,000+ and among Florida&rsquo;s fastest-growing small cities",
        "distinction": "A veterans&rsquo;-colony lakefront town on East Lake Toho, now the center of the booming Narcoossee growth corridor",
        "lat": "28.2489",
        "lng": "-81.2812",
        "neighborhoods": [
            "Historic St. Cloud", "Narcoossee corridor", "Hanover Lakes", "Twin Lakes",
            "Stevens Plantation", "Harmony", "Sunbrooke", "Canoe Creek corridor",
            "Lakeshore Park district",
        ],
        "profile": "St. Cloud is two towns wearing one name. The original grid &mdash; laid out a century ago as a veterans&rsquo; colony &mdash; runs on brick-accented streets and lakefront blocks along East Lake Toho, where original slabs and ribbon drives are far past their service life and owners want replacements that respect the old town&rsquo;s scale. The Narcoossee corridor is the other town: Hanover Lakes with its canal-front lots, Twin Lakes&rsquo; active-adult streets, Harmony&rsquo;s conservation-minded villages &mdash; thousands of new homes whose builder-minimum concrete is already queuing for widening, paver conversion, and pool-deck work. It is the same dual market we serve across Central Florida, compressed into one fast-growing city, and it is exactly the profile where a published price table and a written proposal in one business day beat the fly-by-night quotes this corridor attracts.",
        "profile_short": "St. Cloud &mdash; historic East Lake Toho grid plus the booming Narcoossee corridor (Hanover Lakes, Twin Lakes, Harmony). Century-old slabs downtown, builder-upgrade cycles in the new villages.",
        "terrain_note": "Lakefront and canal-front lots carry high water tables &mdash; bases get elevation-checked against wet-season water, and falls carry runoff to the engineered drainage, not the neighbor&rsquo;s lot.",
        "landmarks": "St. Cloud Lakefront Park on East Lake Toho, the historic downtown grid, Harmony&rsquo;s dark-sky preserve streets, the Narcoossee Road corridor",
        "demand_note": "Replacement-cycle work in the historic grid; widening, paver conversion, and pool decks across the Narcoossee-corridor villages",
        "review_note": "City of St. Cloud or Osceola County permitting by section; HOA review in the newer master-planned communities.",
    },
    "davenport": {
        "name": "Davenport",
        "slug": "davenport",
        "tier": 2,
        "county": "Polk County",
        "state": "FL",
        "zips": ["33837", "33896", "33897"],
        "population": "10,000+ in the city · tens of thousands across the Four Corners growth area",
        "distinction": "The Polk County corner of Four Corners &mdash; resort-residential growth where the Disney economy meets the I-4 corridor",
        "lat": "28.1614",
        "lng": "-81.6017",
        "neighborhoods": [
            "Providence", "Solterra Resort", "Astonia", "Forest Lake",
            "Windsor Island Resort", "Bella Trae", "Loma Vista", "Horse Creek",
            "Historic Downtown Davenport",
        ],
        "profile": "Davenport lives a double life. On one side, resort communities &mdash; Solterra, Windsor Island, the vacation-home belts off US-27 &mdash; run pool decks and patios hard, with guest turnover punishing every surface and owners needing repairs and refreshes on a schedule, not someday. On the other, Providence, Astonia, Forest Lake, and the residential subdivisions climbing the ridge give Polk&rsquo;s corner of Four Corners the familiar Florida cycle of builder-minimum driveways heading into widening and paver upgrades. The Lake Wales Ridge adds sandhill topography most of metro Orlando lacks: fast-draining deep sands that swallow compaction effort unless the base is built in disciplined lifts. Between resort durability and ridge-sand base work, Davenport rewards the unglamorous parts of this trade &mdash; which happen to be the parts we systematized.",
        "profile_short": "Davenport &mdash; Polk&rsquo;s Four Corners: resort communities (Solterra, Windsor Island) running pool decks hard, plus Providence and the ridge subdivisions entering the driveway-upgrade cycle.",
        "terrain_note": "Lake Wales Ridge sands drain fast and compact stubbornly &mdash; bases go in thinner lifts with more passes, or the surface settles no matter how good the finish looks.",
        "landmarks": "Providence Golf Club, Posner Park, the US-27 corridor, Historic Downtown Davenport, the I-4/ChampionsGate interchange",
        "demand_note": "High-cycle resort pool decks and patios, plus residential driveway widening and paver conversions in Providence and the ridge subdivisions",
        "review_note": "City of Davenport or Polk County permitting; resort communities and Providence run HOA/design review.",
    },
    "champions-gate": {
        "name": "ChampionsGate",
        "slug": "champions-gate",
        "tier": 2,
        "county": "Osceola County",
        "state": "FL",
        "zips": ["33896"],
        "population": "Resort-residential community of several thousand homes",
        "distinction": "A golf-resort community at the I-4 gateway &mdash; the Omni resort, two championship courses, and one of Florida&rsquo;s densest vacation-home markets",
        "lat": "28.2558",
        "lng": "-81.6431",
        "neighborhoods": [
            "The Retreat at ChampionsGate", "The Country Club at ChampionsGate",
            "Stoneybrook South", "Vistas at ChampionsGate", "Bella Trae (adjacent)",
        ],
        "profile": "ChampionsGate concentrates a very specific hardscape economy: vacation homes that work for a living. In the Retreat and the resort sections, pool decks host new guests weekly &mdash; surfaces take five years of family wear in one, sealers burn off on an accelerated calendar, and repairs have to be scheduled into booking gaps and finished on time. In the Country Club and Stoneybrook South, primary and second homeowners run the more familiar cycle of paver upgrades, lanai extensions, and golf-cart-friendly drives. Everything is governed by community design review, and everything is on a clock. Our fit here is process: written proposals in one business day, real start windows, and a forty-eight-checkpoint standard that doesn&rsquo;t need a second visit to fix the first one &mdash; because in a rental calendar, the redo is the real cost.",
        "profile_short": "ChampionsGate &mdash; golf-resort community where vacation-home pool decks work for a living. Accelerated wear cycles, booking-gap scheduling, and design-reviewed paver and lanai work.",
        "terrain_note": "Flat, engineered resort land with strict drainage plans &mdash; and pool decks whose commercial-grade wear cycle demands sealers and joint sand rated for it.",
        "landmarks": "Omni Orlando Resort, the International and National golf courses, ChampionsGate Village, the I-4 gateway interchange",
        "demand_note": "Rental-cycle pool-deck rebuilds and refreshes, paver upgrades in the Country Club sections, and golf-cart-friendly drive work",
        "review_note": "Osceola County permitting; ChampionsGate community design review governs visible hardscape.",
    },
}
