# Windermere Concrete — city data (part 1 of 4): Tier-1 west Orange core.
# Schema: name, slug, tier, county, zips, population, distinction, lat, lng,
#         neighborhoods, profile, profile_short, terrain_note, landmarks,
#         demand_note, review_note
CITIES = {
    "windermere": {
        "name": "Windermere",
        "slug": "windermere",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["34786"],
        "population": "3,500 in town limits · 30,000+ in the greater 34786 area",
        "distinction": "Home of the Butler Chain of Lakes — an Outstanding Florida Waterway — and some of the highest-value residential real estate in Central Florida",
        "lat": "28.4953",
        "lng": "-81.5348",
        "neighborhoods": [
            "Isleworth", "Keene&rsquo;s Pointe", "Chaine du Lac", "Lake Butler Sound",
            "Reserve at Belmere", "Belmere Village", "Waterford Pointe", "Butler Bay",
            "Manors at Butler Bay", "Windermere Downs", "Windermere Club", "Silver Woods",
            "Tildens Grove", "Casabella", "Glenmuir", "The Willows", "Estates at Windermere",
            "Aladar on Lake Butler",
        ],
        "profile": "Windermere is where this company keeps its name and its standard. Inside the town limits, sand-and-gravel streets and century-old oaks frame lakefront estates on Lake Down, Lake Butler, and Wauseon Bay; outside them, the 34786 corridor stacks gated communities &mdash; Isleworth, Keene&rsquo;s Pointe, Lake Butler Sound, Reserve at Belmere &mdash; where a driveway is part of the architecture, not just a parking surface. The work here runs to circular motor courts in clay brick and travertine, pool decks that step down toward Butler Chain water, and summer kitchens on paver terraces. Nearly every community routes hardscape through an architectural review committee, and the town itself guards its rural character closely, so material choices, drainage, and setbacks are scrutinized before anything is approved. That is the environment our process was built for: sample boards prepared for the ARC, bases engineered for lakefront sand, and finishes chosen to sit quietly beside seven-figure architecture rather than shout at it.",
        "profile_short": "Windermere &mdash; the Butler Chain town of gated lakefront communities (Isleworth, Keene&rsquo;s Pointe, Lake Butler Sound). Estate driveways, travertine pool decks, and ARC-reviewed hardscape are the daily work here.",
        "terrain_note": "Lakefront lots on the Butler Chain sit on deep, fast-draining sugar sand with a water table that rises sharply in the summer wet season &mdash; bases must be compacted in lifts and surfaces pitched decisively away from both the house and the water.",
        "landmarks": "Butler Chain of Lakes, downtown Windermere Town Square, Fernwood Park, the Windermere Farmers Market, Lake Down boat ramp, the sand streets of the historic town grid",
        "demand_note": "Estate driveway rebuilds in brick and travertine, Butler Chain pool decks, and ARC-governed paver upgrades across the gated 34786 communities",
        "review_note": "Town of Windermere permitting inside town limits; Orange County elsewhere in 34786. Nearly every gated community adds its own ARC review on top.",
    },
    "dr-phillips": {
        "name": "Dr. Phillips",
        "slug": "dr-phillips",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["32819", "32836"],
        "population": "12,000+ households across the Sand Lake corridor",
        "distinction": "Home to Bay Hill &mdash; host of the PGA Tour&rsquo;s Arnold Palmer Invitational &mdash; and Orlando&rsquo;s Restaurant Row",
        "lat": "28.4494",
        "lng": "-81.4923",
        "neighborhoods": [
            "Bay Hill", "Phillips Landing", "Emerson Pointe", "Vizcaya", "Toscana",
            "Sand Lake Point", "Sand Lake Hills", "Orange Tree", "Turtle Creek",
            "Torey Pines", "Cypress Point", "Parkside", "Royal Cypress Preserve",
            "Ruby Lake", "Estates at Phillips Landing",
        ],
        "profile": "Dr. Phillips is the established side of southwest Orlando money: golf-course streets around Arnold Palmer&rsquo;s Bay Hill Club, guard-gated enclaves like Phillips Landing and Emerson Pointe on the Butler Chain&rsquo;s eastern lobes, and 1980s&ndash;90s neighborhoods off Sand Lake Road whose original builder concrete is now decades past its service life. That mix produces two steady kinds of work. In the gated communities, owners commission paver and travertine motor courts, resurfaced pool decks, and outdoor-living terraces that have to clear HOA architectural review. In Sand Lake Hills, Orange Tree, and Turtle Creek, the job is more often surgical: tear out a cracked forty-year-old driveway, rebuild the base correctly, and pour or pave something that matches a renovated house. Between Restaurant Row traffic and mature oak roots that heave old walkways, Dr. Phillips rewards a contractor who saw-cuts clean lines, protects landscaping, and gets the drainage right the first time.",
        "profile_short": "Dr. Phillips &mdash; Bay Hill, Restaurant Row, and the guard-gated enclaves of southwest Orlando. Aging 1980s&ndash;90s builder concrete plus estate-level paver and travertine work behind the gates.",
        "terrain_note": "Mature-canopy lots mean oak roots under old slabs and walkways; root-heaved concrete needs full removal and a rebuilt, root-barriered base &mdash; not a skim coat over a moving problem.",
        "landmarks": "Arnold Palmer&rsquo;s Bay Hill Club &amp; Lodge, Restaurant Row on Sand Lake Road, Dr. Phillips Community Park, Big Sand Lake, Dr. P. Phillips YMCA",
        "demand_note": "Driveway tear-out-and-replace in the Sand Lake neighborhoods; paver motor courts, travertine pool decks, and HOA-reviewed hardscape in Bay Hill and the gated communities",
        "review_note": "Unincorporated Orange County permitting; HOA architectural review in Bay Hill, Phillips Landing, Emerson Pointe, Vizcaya, and most gated communities.",
    },
    "horizon-west": {
        "name": "Horizon West",
        "slug": "horizon-west",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["34787"],
        "population": "75,000+ and climbing — among the fastest-growing planned communities in the United States",
        "distinction": "A master-planned network of villages between Windermere and the Disney border, built almost entirely since 2005",
        "lat": "28.4245",
        "lng": "-81.6103",
        "neighborhoods": [
            "Hamlin", "Independence", "Summerport", "Summerlake", "Waterleigh",
            "Watermark", "Lakeshore", "Silverleaf", "Isles of Lake Hancock",
            "Encore at Ovation", "Lakes of Windermere", "Orchard Hills",
            "Panther View", "Ravenna", "Hickory Hammock",
        ],
        "profile": "Horizon West is new-Florida at full speed: village after village &mdash; Hamlin, Waterleigh, Independence, Summerlake &mdash; platted around Lake Hancock and the western edge of Disney property, with thousands of homes closed in the last decade and thousands more coming. Practically every one of them shipped with the same builder package: a plain broom-finish driveway sized to the minimum, a small concrete lanai pad, and a yard waiting for a pool. The upgrade wave is our core work here &mdash; widening tight two-car driveways so they actually fit two SUVs, replacing builder concrete with paver systems the HOA palette allows, and building the pool decks and paver terraces the original contract never included. Because these are deed-restricted villages with active HOAs and tight lot lines, drainage to the engineered swales matters: a surface that sheds water onto a neighbor&rsquo;s lot is a violation letter waiting to happen. We build to the plat, to the palette, and to the Craft Code.",
        "profile_short": "Horizon West &mdash; Hamlin, Waterleigh, Independence, and the villages around Lake Hancock. Builder-minimum driveways and bare lanais built since 2005 drive constant widening, paver-upgrade, and pool-deck work.",
        "terrain_note": "Former citrus land graded flat for development &mdash; lots drain to engineered swales, so every new surface must respect the drainage plan or the HOA and the county will both notice.",
        "landmarks": "Hamlin Town Center, Cinépolis Hamlin, Lake Hancock, Orange County National Golf Center, Flamingo Crossings Town Center, the SR-429 corridor",
        "demand_note": "Driveway widening and paver conversions on builder-minimum drives, new pool decks behind new pools, and HOA-palette paver terraces across the villages",
        "review_note": "Orange County permitting; every Horizon West village runs deed restrictions and most require HOA approval of driveway and hardscape changes.",
    },
    "winter-garden": {
        "name": "Winter Garden",
        "slug": "winter-garden",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["34787", "34777"],
        "population": "50,000+ city residents",
        "distinction": "A restored brick-street downtown on Lake Apopka&rsquo;s south shore, anchored by the West Orange Trail and Plant Street Market",
        "lat": "28.5653",
        "lng": "-81.5862",
        "neighborhoods": [
            "Historic Downtown Winter Garden", "Stoneybrook West", "Johns Lake Pointe",
            "Stone Creek", "Black Lake Park", "Carriage Pointe", "Covington Chase",
            "Oxford Chase", "Belle Meade", "Crown Point Springs", "Tucker Ranch",
            "Twinwaters", "Hickory Hammock", "Emerald Ridge", "Regal Pointe",
        ],
        "profile": "Winter Garden runs on two clocks. Downtown, the brick streets and bungalow blocks around Plant Street date to the citrus era &mdash; here the work is careful: replacing cracked ribbon driveways beside 1920s houses, pouring walkways that defer to historic frontage, and matching hardscape to a district people fiercely protect. South and west of downtown, the clock runs fast: Stoneybrook West, Johns Lake Pointe, Oxford Chase, and the newer subdivisions toward Clermont carry the same builder-concrete-to-paver upgrade cycle as the rest of west Orange, plus a heavy pool-deck market on the Johns Lake and Black Lake chains. Between the two sits the West Orange Trail, which keeps property pride &mdash; and curb-appeal spending &mdash; unusually high for a city this size. Whether the job is a herringbone brick apron that belongs beside a heritage oak or a two-hundred-square-yard paver drive in a gated section, the grade, base, and joints get the same forty-eight checkpoints.",
        "profile_short": "Winter Garden &mdash; brick-street historic downtown plus fast-growing subdivisions toward Johns Lake. Heritage-sensitive concrete work downtown; paver upgrades and pool decks in the newer gated sections.",
        "terrain_note": "Proximity to Lake Apopka means pockets of organic, mucky soil in low-lying sections &mdash; we probe before we price, because a driveway floated over muck fails no matter how good the pour is.",
        "landmarks": "Plant Street Market, the West Orange Trail, downtown&rsquo;s brick streets and clock tower, Newton Park on Lake Apopka, Winter Garden Farmers Market, Crooked Can Brewing",
        "demand_note": "Historic-district driveway and walkway rebuilds downtown; paver driveways, pool decks, and patio terraces in Stoneybrook West and the Johns Lake corridor",
        "review_note": "City of Winter Garden permitting; the historic downtown district carries design guidelines, and the gated communities add HOA review.",
    },
    "gotha": {
        "name": "Gotha",
        "slug": "gotha",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["34734"],
        "population": "2,000+ in the hamlet and surrounding estate lots",
        "distinction": "An 1885 German settlement turned estate-lot enclave, wedged between Windermere and Winter Garden",
        "lat": "28.5278",
        "lng": "-81.5231",
        "neighborhoods": [
            "Historic Gotha", "Citrus Oaks", "Falcon Pointe", "Braemar",
            "Lake Fischer Estates", "Lake Nally Woods", "Hempel Avenue corridor",
            "Park Avenue Estates", "Gotha Estates",
        ],
        "profile": "Gotha is the quiet card in west Orange&rsquo;s deck: a nineteenth-century settlement of oak canopies, small lakes, and acre-plus estate lots that never incorporated and never got busy. Homeowners here tend to hold property for decades, which shapes the work &mdash; long private drives that need honest tear-out and replacement rather than patching, circular aprons in front of custom homes, and pool decks and terraces added as families settle in for the long haul. Because lots are large and many drives are long, base engineering matters more here than almost anywhere we work: a three-hundred-foot drive multiplies every shortcut a contractor takes. There are no cookie-cutter HOAs across most of Gotha, but there is something stricter &mdash; neighbors who have watched the same lane for thirty years. Work that looks temporary gets noticed. Ours doesn&rsquo;t.",
        "profile_short": "Gotha &mdash; historic 1885 hamlet of oak-canopy estate lots between Windermere and Winter Garden. Long private drives, circular aprons, and legacy-property pool decks with almost no contractor competition.",
        "terrain_note": "Estate lots mix sugar sand with pockets of organic soil near the small lakes; long drives demand lift-compacted bases and drainage planned across the full run, not just at the garage.",
        "landmarks": "Nehrling Gardens, Yellow Dog Eats in the old general store, Lake Olivia, Lake Fischer, the Hempel Avenue oak canopy",
        "demand_note": "Long-run driveway replacements on estate lots, circular motor courts, and legacy-home patio and pool-deck additions",
        "review_note": "Unincorporated Orange County permitting; few HOAs &mdash; but heritage-lot drainage and tree protection deserve real attention.",
    },
    "oakland": {
        "name": "Oakland",
        "slug": "oakland",
        "tier": 1,
        "county": "Orange County",
        "state": "FL",
        "zips": ["34760"],
        "population": "5,000+ and growing with Oakland Park&rsquo;s build-out",
        "distinction": "A 19th-century railroad town on Lake Apopka&rsquo;s south shore, reborn around the West Orange Trail and the Oakland Park traditional-neighborhood development",
        "lat": "28.5550",
        "lng": "-81.6331",
        "neighborhoods": [
            "Oakland Park", "Historic Oakland", "Hull Island", "Johns Landing",
            "Longleaf at Oakland", "Oakland Trails", "Trailside Station",
            "Winters Landing", "Briley Farm area",
        ],
        "profile": "Oakland pairs one of Central Florida&rsquo;s oldest town grids with one of its most deliberate new ones. The historic side &mdash; sand lanes, cracker cottages, live oaks planted before the freeze of 1894 &mdash; generates modest but exacting work: walkway and driveway rebuilds that must sit politely beside century-old frontage. Oakland Park, the town&rsquo;s flagship traditional-neighborhood development, generates the opposite: brand-new craftsman-style homes on alley-loaded lots where pavers, front porches, and street trees are part of the design code itself, and where driveway aprons, courtyard patios, and rear-lane parking pads have to match an explicit pattern book. Add Hull Island and Johns Landing on the Johns Lake side, and Oakland gives a hardscape crew a full range &mdash; heritage restraint on one street, pattern-book precision two blocks over. Few contractors bother with a town this small. That is precisely why we do.",
        "profile_short": "Oakland &mdash; historic railroad town plus the Oakland Park TND on Lake Apopka&rsquo;s south shore. Pattern-book paver work in Oakland Park, heritage-sensitive rebuilds in the old grid.",
        "terrain_note": "South-shore soils grade from clean sand on the ridge to organic muck toward Lake Apopka &mdash; subgrade probing decides the base spec here, lot by lot.",
        "landmarks": "The West Orange Trail through the oak tunnel, Oakland Nature Preserve, Speer Park, the historic town hall, Lake Apopka shoreline",
        "demand_note": "Pattern-book driveways, courtyard patios, and rear-lane pads in Oakland Park; heritage walkway and drive rebuilds in the historic grid",
        "review_note": "Town of Oakland permitting; Oakland Park enforces a design pattern book that governs hardscape materials and layout.",
    },
}
