# Windermere Concrete — service data (part 3 of 4): sidewalks/walkways, paver driveways, paver patios.
SERVICES = {
    "sidewalks-walkways": {
        "name": "Sidewalks, Walkways &amp; Steps",
        "slug": "sidewalks-walkways",
        "short": "Sidewalks &amp; Walkways",
        "h1_phrase": "Sidewalks, Walkways &amp; Steps",
        "numeral": "07",
        "group": "Concrete",
        "answer_block": "Concrete walkways in the Windermere area run <strong>$9&ndash;$15 per square foot installed</strong>; formed steps run <strong>$300&ndash;$900 per step</strong> depending on width and finish. Landscape curbing runs <strong>$8&ndash;$15 per linear foot</strong>. Most walkway projects complete in two to four site days.",
        "intro_lead": "Front walks, garden paths, formed steps, and landscape curbing &mdash; the connective tissue of a property, built straight, drained right, and finished to match the home.",
        "craft_p1": "Walkways are judged from twenty feet away and lived on from two. From twenty feet, what registers is line: a walk that runs true, borders that parallel the bed they frame, curves that flow instead of wobble. From two feet, what registers is safety and comfort &mdash; consistent tread, no lips or trip edges, a surface that grips in the rain and drains before it puddles. We build for both distances. Layouts are staked and strung for approval before excavation; slopes carry water off the path instead of down it; and where a walk meets a drive, a porch, or a public sidewalk, the transitions land flush. Under the Craft Code, even a garden path gets a compacted base and jointing plan &mdash; because a forty-foot walk that cracks and heaves is exactly as annoying as a driveway that does, and cheaper to prevent.",
        "craft_p2": "Steps and curbing round out the scope. <strong>Formed concrete steps</strong> handle Florida&rsquo;s modest grade changes &mdash; porch approaches, lakefront yards, sunken patios &mdash; with riser heights kept dead-consistent, since an uneven step is a stumble engineered into the property. <strong>Landscape curbing</strong> frames beds and tree rings in continuous formed concrete that mowers respect and mulch stays behind. Finishes across all of it can be broom, stamped, or exposed aggregate, matched to your existing hardscape or the new work we&rsquo;re building alongside. And for front entries in the estate communities, we design wider approaches &mdash; five and six feet, bordered, sometimes lit &mdash; because the walk to the front door is the property&rsquo;s handshake, and code-minimum three feet reads exactly like what it is.",
        "scope_items": [
            "Front-entry walks &amp; widened approaches",
            "Garden &amp; connector paths",
            "Public-sidewalk repair &amp; replacement sections",
            "Formed concrete steps &amp; landings",
            "Stoop &amp; porch approach rebuilds",
            "Landscape curbing &amp; bed edging",
            "Tree-ring &amp; planter surrounds",
            "Trip-hazard removal &amp; grade corrections",
            "Broom, stamped &amp; exposed-aggregate finishes",
            "Root-zone reroutes around protected trees",
            "Lighting-conduit sleeves placed before the pour",
            "ADA-conscious slopes &amp; landings where applicable",
        ],
        "options_rows": [
            ("Broom-finish walk", "Everyday paths &amp; sidewalks", "Clean, grippy, budget-honest"),
            ("Stamped walkway", "Entries &amp; garden features", "Stone character underfoot"),
            ("Exposed aggregate", "Estate entries", "Washed-stone texture, hides wear"),
            ("Formed steps", "Grade changes &amp; porches", "Consistent risers, matched finish"),
        ],
        "pricing_rows": [
            ("Broom-finish walkway", "$9&ndash;$15 / sq ft", "Formed, reinforced &amp; jointed"),
            ("Stamped / decorative walkway", "$14&ndash;$22 / sq ft", "Pattern, color &amp; sealer"),
            ("Exposed-aggregate walk", "$13&ndash;$19 / sq ft", "Washed architectural texture"),
            ("Formed steps &amp; landings", "$300&ndash;$900 / step", "Width &amp; finish dependent"),
            ("Landscape curbing", "$8&ndash;$15 / linear ft", "Continuous formed edging"),
            ("Sidewalk section replacement", "$10&ndash;$16 / sq ft", "Demo &amp; haul included"),
            ("Trip-hazard grinding", "$150&ndash;$450 / location", "Fast, clean corrections"),
        ],
        "faqs": [
            ("How wide should a front walkway be?",
             "Code lets you get away with three feet; comfort starts at four; presence starts at five. Two people walking together need about four and a half feet, which is why the three-foot builder ribbon always feels like a single-file trail. For the estate communities we usually design front approaches at five to six feet with a border detail &mdash; the proportion reads correctly against a larger fa&ccedil;ade, and the incremental cost over a code-minimum walk is smaller than most owners expect. Garden and connector paths can drop to three feet gracefully; the front door deserves better."),
            ("Whose responsibility is a broken public sidewalk in front of my house?",
             "It varies by jurisdiction &mdash; in some west Orange communities the county or city maintains public walks, in others the abutting owner is responsible for damage (especially from your own tree roots), and HOA streets are their own world. We handle it pragmatically: we can replace the failed sections to the local public-works standard, coordinate the permit the jurisdiction requires for right-of-way work, and document the repair. If the walk is genuinely the county&rsquo;s to fix, we will tell you that too, along with how to report it &mdash; no point paying for public work that a phone call gets done."),
            ("Can you route a walkway around our big oak without killing it?",
             "Yes &mdash; and around here, that oak is often protected by ordinance, so the routing isn&rsquo;t optional anyway. The techniques are established: curve the path outside the critical root zone where possible; where it must pass closer, we bridge sensitive roots with a floating, thickened section over structural fill instead of excavating through them, or narrow the walk locally. What we never do is chop primary roots to keep a line straight &mdash; that trades a curve you&rsquo;d stop noticing in a month for a declining tree and, in Winter Park or Windermere, a code violation. The tree was there first; the walk can bend."),
            ("Do your steps meet code for riser height?",
             "Yes, and more importantly they meet the consistency rule that makes stairs safe: riser heights within a small tolerance of each other, every step. The human gait memorizes the first riser and repeats it blind &mdash; a step that&rsquo;s three-quarters of an inch off is where people go down. We form risers to uniform height, treads to consistent depth with a slight wash for drainage, and finishes textured for wet grip. Where a landing or handrail is required by the geometry, we flag it in the proposal rather than discover it at inspection."),
            ("What does walkway and curbing work cost here?",
             "Broom-finish walks run $9&ndash;$15 per square foot installed; stamped and exposed-aggregate work $13&ndash;$22. Formed steps price at $300&ndash;$900 each depending on width and finish; continuous landscape curbing at $8&ndash;$15 per linear foot. A typical forty-foot front walk lands between $1,400 and $3,600. As with everything we build, the written proposal breaks the number into line items &mdash; and walkways are the easiest place to phase work if you&rsquo;re sequencing a bigger outdoor plan."),
        ],
        "not_included": "We do not build retaining walls over four feet or structural stairs attached to buildings &mdash; site walks, garden steps, and landscape-grade transitions are the scope here.",
    },
    "paver-driveways": {
        "name": "Paver Driveways",
        "slug": "paver-driveways",
        "short": "Paver Driveways",
        "h1_phrase": "Paver Driveways",
        "numeral": "08",
        "group": "Pavers &amp; Travertine",
        "answer_block": "A paver driveway in the Windermere and west Orlando market runs <strong>$14&ndash;$24 per square foot installed</strong> for concrete pavers and <strong>$18&ndash;$30</strong> for clay brick. The system &mdash; compacted base, bedding sand, interlocked field, edge restraint, polymeric joints &mdash; is what you&rsquo;re buying; the pavers are just the visible layer.",
        "intro_lead": "Interlocking paver and clay-brick driveways built as engineered systems &mdash; the estate standard for the Butler Chain communities, and the upgrade every ARC palette already approves of.",
        "craft_p1": "A paver driveway is a load-bearing system that happens to be beautiful. Under the surface you choose from the catalog sits everything that decides whether it stays flat: eight to ten inches of crushed rock compacted in lifts, a screeded bedding course, geotextile separation where the soil demands it, and concrete edge restraint locking the field so three tons of SUV turning in place can&rsquo;t walk the pattern apart. This is where the Craft Code earns its keep &mdash; the base gets probed, compacted, measured, and photographed before a single paver is placed, because a rutted paver driveway is never a paver problem. It is a base problem wearing nice clothes.",
        "craft_p2": "Then comes the part you actually see, and in this market it matters enormously. We build in concrete pavers across the full architectural range &mdash; tumbled old-world cobbles, crisp large-format planks, permeable systems where drainage rules demand them &mdash; and in <strong>genuine clay brick</strong>, the material Winter Park&rsquo;s streets and Windermere&rsquo;s estates were built on, which holds its color for a century because the color is the clay. Patterns are chosen for load as well as looks: herringbone locks tightest under turning tires; running bond and plank layouts suit modern fa&ccedil;ades; borders and soldier courses frame the field and satisfy the ARC drawing. Every driveway ships with polymeric-sand joints, activated and cured, and a written warranty that covers the system &mdash; not just the pieces.",
        "scope_items": [
            "New paver driveways &mdash; standard, circular &amp; motor-court",
            "Builder-concrete tear-out &amp; paver conversion",
            "Clay-brick driveways &amp; aprons",
            "Large-format &amp; plank paver systems",
            "Permeable paver systems for drainage-sensitive lots",
            "Excavation &amp; lift-compacted crushed-rock base",
            "Geotextile separation on demanding soils",
            "Concrete edge restraint &mdash; the field can&rsquo;t migrate",
            "Herringbone, running-bond &amp; custom pattern layouts",
            "Borders, soldier courses &amp; contrast banding",
            "Polymeric joint sand, activated &amp; cured",
            "ARC / HOA sample boards &amp; submittal documentation",
            "Sealing &mdash; natural, enhanced, or wet-look",
        ],
        "options_rows": [
            ("Concrete pavers", "The versatile standard", "Full color/format range, strongest value"),
            ("Clay brick", "Estates, historic districts", "Century color &mdash; the tone is the clay itself"),
            ("Large-format / plank", "Modern architecture", "Clean lines, fewer joints"),
            ("Permeable system", "Drainage-sensitive lots", "Rain soaks through, not runs off"),
        ],
        "pricing_rows": [
            ("Concrete paver driveway", "$14&ndash;$24 / sq ft", "Full system, installed"),
            ("Clay-brick driveway", "$18&ndash;$30 / sq ft", "Genuine kiln-fired brick"),
            ("Builder-concrete conversion", "$16&ndash;$26 / sq ft", "Demo &amp; haul included"),
            ("Permeable paver system", "$17&ndash;$28 / sq ft", "Open-graded base included"),
            ("Circular / motor-court layout", "$18&ndash;$30 / sq ft", "Radius cutting &amp; banding"),
            ("Border &amp; soldier-course detail", "$7&ndash;$14 / linear ft", "Contrast or matched"),
            ("Sealing (new install)", "$1.50&ndash;$3 / sq ft", "Natural to wet-look"),
        ],
        "faqs": [
            ("Why do paver driveways cost more than concrete &mdash; and when are they worth it?",
             "You are paying for a system with more layers and more labor: deeper excavation, more base rock, hand-laid field, edge restraint, and jointing. What that buys is repairability and longevity &mdash; a paver drive never needs to be &lsquo;replaced&rsquo; the way a slab does, because any settled or stained section lifts and relays invisibly, and the surface itself routinely outlasts two generations of concrete driveways. It is worth it when you plan to hold the home, when your community&rsquo;s aesthetics reward it (in much of Windermere, pavers are simply the neighborhood standard), and when resale is part of the math. When it isn&rsquo;t &mdash; short hold, rental property, tight budget &mdash; we will happily pour you excellent concrete instead."),
            ("Will the pavers settle or spread over time?",
             "Not if the system under them was built &mdash; and that qualifier is the entire paver industry in one sentence. Settling means the base wasn&rsquo;t compacted in lifts or the soft subgrade was never corrected; spreading means edge restraint was skipped or set on dirt. Our installs carry eight to ten inches of lift-compacted rock under vehicle areas, concrete edge restraint around the full perimeter, and joint sand that locks the field into a single mat. That is also why we can put the anti-settlement promise in writing: the failure modes have names, and every one of them has a checkpoint."),
            ("Clay brick or concrete pavers?",
             "Clay brick is fired color &mdash; it cannot fade, because the tone is the material itself; it carries the historic authority this area&rsquo;s oldest streets are built on; and it costs more per foot. Concrete pavers offer triple the shapes, sizes, and blends, engineer precisely for vehicle load, and repair from stock decades later. Aesthetically: brick belongs beside traditional and historic architecture; concrete pavers serve everything from Tuscan to modern. Roughly, brick runs $18&ndash;$30 installed against $14&ndash;$24 for concrete pavers. In ARC communities, check the palette first &mdash; several around here list specific approved blends, and we keep those lists on file."),
            ("How do you handle the HOA approval for a driveway conversion?",
             "Conversion from builder concrete to pavers is the single most common ARC submittal in the newer west Orange communities, and boards approve it routinely &mdash; when the paperwork is right. We assemble the package with your proposal: product name and blend, a physical or photographic sample, the pattern and border drawing, and the drainage note reviewers increasingly ask for. You or your manager submits; we build to the approved sheet. The step we insist on is sequence &mdash; approval, then demolition. A half-converted driveway waiting on a denied variance is a situation we refuse to create."),
            ("What maintenance does a paver driveway actually need?",
             "Less than its reputation, more than zero. Rinse and spot-clean as life happens; top up joint sand where a pressure washer or storm scours it; and re-sand-and-seal on a two-to-four-year cycle depending on sun and traffic. That cycle is the whole secret to the &lsquo;still looks new&rsquo; paver driveways you see in the older communities &mdash; and it is a service we offer on a reminder schedule, so it happens on a date instead of when the weeds announce it. Between cycles, a paver drive asks essentially nothing."),
        ],
        "not_included": "We do not lay pavers over failing concrete or un-corrected soft ground &mdash; every conversion gets a real base, because the warranty we sign has to survive the driveway you drive on.",
    },
    "paver-patios": {
        "name": "Paver Patios &amp; Walkways",
        "slug": "paver-patios",
        "short": "Paver Patios",
        "h1_phrase": "Paver Patios &amp; Walkways",
        "numeral": "09",
        "group": "Pavers &amp; Travertine",
        "answer_block": "Paver patios in the Windermere and Orlando area run <strong>$13&ndash;$23 per square foot installed</strong>, with fire pits from <strong>$1,200&ndash;$4,500</strong> and spaced-paver garden patios from <strong>$15&ndash;$26</strong>. Design, base engineering, edge restraint, and polymeric jointing are included in the number &mdash; not sold as extras.",
        "intro_lead": "Outdoor rooms in interlocking stone &mdash; entertaining terraces, garden walks, fire-pit courts, and the spaced-paver-and-gravel patios that define current Florida landscape design.",
        "craft_p1": "A paver patio is landscape architecture you live on, and the design conversation comes before any talk of product. How many people do you actually host? Where does the afternoon sun land, and where does the screen porch shadow fall? Does the grill live here year-round? Which door does traffic really use? We sketch the answers into zones &mdash; dining, lounge, fire, path &mdash; then scale the hardscape to the furniture and the life, staking the footprint on your grass for a walk-through before anything is dug. The pattern language follows the architecture: tumbled cobbles and herringbone beside traditional homes; large-format planks with tight joints beside modern ones; borders that end the field on purpose instead of wherever the pallet ran out.",
        "craft_p2": "The current signature of Florida landscape design &mdash; the <strong>spaced-paver patio</strong>, large-format slabs set with open joints of turf, river gravel, or shell &mdash; is a system we build often and build correctly: each slab on its own compacted bed so the checkerboard stays dead-level while the joints stay soft. Around it, the supporting cast: <strong>fire-pit courts</strong> ringed in matching block, <strong>garden walkways</strong> that connect zones without mud, <strong>paver steps</strong> where the yard changes level. Under all of it, the same non-negotiables as our driveways &mdash; compacted base, edge restraint, polymeric or specified joint fill &mdash; scaled to foot traffic instead of axle loads. The result is a backyard that works as hard as your living room, and holds its lines while the garden around it grows in.",
        "scope_items": [
            "Entertaining terraces &amp; outdoor dining rooms",
            "Spaced-paver patios with turf or gravel joints",
            "Garden walkways &amp; connector paths",
            "Fire-pit courts &amp; seating rings",
            "Paver steps &amp; terraced grade transitions",
            "Grill &amp; outdoor-kitchen surrounds (non-structural)",
            "Lanai &amp; pool-cage paver floors",
            "Compacted base scaled to pedestrian loads",
            "Concrete edge restraint on every field edge",
            "Polymeric sand or specified soft-joint fill",
            "Border, banding &amp; inlay details",
            "Low-voltage lighting sleeves before the field closes",
            "ARC / HOA documentation where required",
        ],
        "options_rows": [
            ("Tumbled cobble", "Traditional &amp; Tuscan homes", "Old-world texture, forgiving repeat"),
            ("Large-format plank", "Modern architecture", "Clean joints, gallery lines"),
            ("Spaced pavers + gravel/turf", "Design-led gardens", "The current Florida signature"),
            ("Clay brick", "Historic &amp; estate settings", "Warmth that never fades"),
        ],
        "pricing_rows": [
            ("Paver patio (standard field)", "$13&ndash;$23 / sq ft", "Full system, installed"),
            ("Spaced-paver / gravel-joint patio", "$15&ndash;$26 / sq ft", "Individual slab bedding"),
            ("Garden walkway", "$12&ndash;$20 / sq ft", "Path-scaled base &amp; edging"),
            ("Fire-pit court &amp; ring", "$1,200&ndash;$4,500", "Pit, surround &amp; field"),
            ("Paver steps", "$250&ndash;$700 / step", "Terraced transitions"),
            ("Clay-brick patio", "$16&ndash;$28 / sq ft", "Genuine kiln-fired brick"),
            ("Sealing (new install)", "$1.50&ndash;$3 / sq ft", "Natural to enhanced"),
        ],
        "faqs": [
            ("What makes the spaced-paver look work &mdash; and what makes it fail?",
             "The look is easy; the levelness is the craft. Each large-format slab in a spaced layout is its own little foundation &mdash; bedded, tamped, and checked individually &mdash; because with open joints there is no interlocked field to average out a lazy spot; every slab reads level or crooked on its own. Failures you see around town come from slabs set on un-compacted spoil (they tilt by year one) and from joint materials chosen wrong &mdash; turf joints need irrigation reach and sun, gravel joints need containment and depth. We build the checkerboard on compacted beds, spec the joint to your yard&rsquo;s light and water, and the pattern stays a pattern."),
            ("Pavers or stamped concrete for our patio?",
             "The criteria that actually decide it: repairability (pavers lift and relay invisibly; stamped repairs are visible patches), surface continuity (stamped is seamless and weed-free; paver joints are honest joints), access (pavers walk through a garden gate wheelbarrow by wheelbarrow; a mixer needs a path), and budget (stamped usually lands somewhat lower installed). Around tree roots and on lots that move, pavers&rsquo; flexibility wins; for a sealed, single-surface outdoor room, stamped wins. We install both at full quality, so our recommendation follows your lot and your priorities &mdash; not our margin."),
            ("Can you build the fire pit itself, or just the patio?",
             "Both &mdash; with an honest boundary. We build wood-burning fire-pit rings and seating courts in masonry units engineered for the heat, sized to keep flame the code-required distance from structures and screen enclosures, and we set the surround field to shed embers onto stone rather than turf. What we coordinate rather than perform: gas plumbing (licensed gas contractor) and any roofed or structural outdoor-kitchen framing. Most of our fire features are complete, hand-off-ready hardscape; where gas or structure enters the scope, we sequence with the right trade instead of pretending to be one."),
            ("How do paver patios handle Florida downpours?",
             "Better than almost any surface, when graded right. The field itself sheds water along designed falls like any patio &mdash; but the joints also relieve pressure, and permeable and spaced systems go further, letting rain soak through to the ground instead of racing to the swale. On heavy-rain lots we often mix systems: a tight-jointed dining terrace pitched to drain, spaced-paver zones where the yard needs to breathe. What no patio survives is a contractor who ignored where the water already wanted to go &mdash; which is why drainage is checkpoint territory in the Craft Code, mapped during Ground Truth before the design is even final."),
            ("What does a paver patio cost in the Orlando area?",
             "Standard fields run $13&ndash;$23 per square foot installed; spaced-paver and gravel-joint designs $15&ndash;$26; clay brick $16&ndash;$28. A 300-square-foot entertaining terrace typically lands between $4,000 and $7,000; add $1,200&ndash;$4,500 for a fire-pit court, $250&ndash;$700 per step where the grade moves. Everything itemizes on the written proposal, which makes phasing painless &mdash; many clients build the terrace this season and the fire court next, on the same pattern and blend we keep on file."),
        ],
        "not_included": "We do not build roofed structures, pergolas, or gas systems &mdash; the hardscape beneath and around them is ours, and we sequence cleanly with your builder or gas contractor.",
    },
}
