# Windermere Concrete — service data (part 4 of 4): travertine pool decks, paver sealing/repair, driveway extensions.
SERVICES = {
    "travertine-pool-decks": {
        "name": "Travertine &amp; Paver Pool Decks",
        "slug": "travertine-pool-decks",
        "short": "Travertine Pool Decks",
        "h1_phrase": "Travertine &amp; Paver Pool Decks",
        "numeral": "10",
        "group": "Pavers &amp; Travertine",
        "answer_block": "A travertine pool deck in the Windermere area runs <strong>$22&ndash;$35 per square foot installed</strong>; premium paver pool decks run <strong>$15&ndash;$26</strong>. Travertine stays remarkably cool underfoot &mdash; typically the coolest walking surface available for a Florida pool &mdash; and it is the default standard around Butler Chain estates.",
        "intro_lead": "Natural travertine, marble, and premium paver pool surrounds &mdash; the coolest surfaces underfoot in Florida, set on engineered bases and detailed to estate standard.",
        "craft_p1": "Travertine earned its place around Florida&rsquo;s best pools honestly: the stone&rsquo;s porous structure keeps its surface temperature dramatically lower than concrete or dense pavers &mdash; barefoot-comfortable in full July sun &mdash; while its tumbled texture grips wet feet and its French-pattern layouts flatter every architectural style from Mediterranean to modern. But natural stone punishes casual installers. Travertine is calibrated thinner than concrete pavers, so the bedding must be screeded flatter; its edges chip if handled carelessly; its pores demand a breathable, stone-specific sealer, never the film-forming products that trap moisture and cloud white. We install travertine weekly, in sand-set and mud-set systems as the site demands, with coping, drains, and cage-track details planned in the drawing stage &mdash; not improvised at the saw.",
        "craft_p2": "The same craft extends across the premium deck materials this market asks for: <strong>marble pavers</strong>, cooler still and unapologetically luxurious; <strong>shellstone and limestone</strong> with their soft coastal faces; <strong>porcelain pavers</strong> where a modern, zero-porosity surface suits the architecture; and <strong>premium concrete pavers</strong> when the budget wants the look without the stone. Around all of them, the details that make a deck read finished: bullnose coping turned cleanly at the waterline, borders mitered at radius corners, deck drains set flush in the field, and falls that carry splash-out away from both the pool and the house. This is the flagship service of this company &mdash; the one our name is built on &mdash; and the Craft Code&rsquo;s forty-eight checkpoints apply to every square foot of it.",
        "scope_items": [
            "Travertine pool decks &mdash; sand-set &amp; mud-set systems",
            "Marble, shellstone, limestone &amp; porcelain decks",
            "Premium concrete-paver pool surrounds",
            "French-pattern, plank &amp; custom layouts",
            "Bullnose coping supply &amp; installation",
            "Remodel overlays on existing sound decks",
            "Deck extensions &amp; sun-shelf surrounds",
            "Flush deck drains &amp; engineered falls",
            "Screen-cage track detailing &amp; anchor coordination",
            "Breathable stone-specific sealing",
            "Outdoor-kitchen &amp; summer-kitchen deck fields",
            "ARC / HOA sample &amp; submittal documentation",
        ],
        "options_rows": [
            ("Travertine (tumbled)", "The Florida estate standard", "Coolest mainstream surface, timeless face"),
            ("Marble pavers", "Statement decks", "Cooler &amp; brighter still; premium budget"),
            ("Shellstone / limestone", "Coastal &amp; organic design", "Soft fossil texture, barefoot-kind"),
            ("Porcelain pavers", "Modern architecture", "Zero porosity, razor-straight lines"),
            ("Premium concrete pavers", "Value with polish", "The look for less; warmer underfoot"),
        ],
        "pricing_rows": [
            ("Travertine deck (sand-set)", "$22&ndash;$32 / sq ft", "Stone, base &amp; install"),
            ("Travertine deck (mud-set)", "$26&ndash;$35 / sq ft", "Mortared over sound concrete"),
            ("Marble paver deck", "$26&ndash;$38 / sq ft", "Premium calibrated stone"),
            ("Shellstone / limestone deck", "$20&ndash;$30 / sq ft", "Coastal-face natural stone"),
            ("Porcelain paver deck", "$18&ndash;$30 / sq ft", "Modern zero-porosity system"),
            ("Premium concrete-paver deck", "$15&ndash;$26 / sq ft", "Full system, installed"),
            ("Bullnose coping", "$18&ndash;$35 / linear ft", "Supplied &amp; set"),
            ("Breathable stone sealing", "$1.75&ndash;$3.50 / sq ft", "Stone-specific chemistry"),
        ],
        "faqs": [
            ("Is travertine really that much cooler than other pool decks?",
             "Yes &mdash; and it is the reason the material dominates Florida&rsquo;s estate pool market. Travertine&rsquo;s porous structure and light mineral color shed solar heat instead of banking it; on the same July afternoon, a travertine deck reads dramatically cooler than gray concrete and meaningfully cooler than dense concrete pavers. Marble runs cooler still. If your family swims barefoot at 3 p.m. &mdash; which is to say, if your family swims in Florida &mdash; surface temperature is not a luxury consideration; it is the difference between a deck you use and a deck you sprint across."),
            ("Sand-set or mud-set travertine &mdash; which is right for my deck?",
             "Sand-set (stone on a compacted base and screeded bedding) is the default for new decks and full rebuilds: it drains well, repairs section by section, and rides Florida&rsquo;s soil movement gracefully. Mud-set (stone mortared to an existing structurally sound slab) is the remodel play: it converts a tired concrete deck to travertine without demolition, sits lower against existing doors and coping, and locks the stone rigid. The deciding inputs are what exists today, the elevations of your doors and cage track, and drainage &mdash; we measure all three at the consultation and spec the system honestly. Both are done every week around here; neither is universally right."),
            ("Does travertine stain or absorb pool chemicals?",
             "Travertine is porous stone &mdash; that porosity is where its coolness comes from &mdash; so it will drink what sits on it: tannin from oak leaves, rust from a forgotten steel chair, oil from the grill. The management is simple and proven: a breathable, stone-specific penetrating sealer that repels liquids without plugging the pores (film-forming sealers are the classic mistake &mdash; they trap moisture and cloud the stone), plus the ordinary habit of rinsing spills and clearing leaf drifts. Pool chlorine at normal levels weathers travertine gently; salt splash is worth rinsing near the waterline. We seal every stone deck we set and put the renewal cycle in the care guide."),
            ("Can you lay travertine over our existing concrete pool deck?",
             "Frequently yes &mdash; the mud-set remodel is one of our most-requested projects in the established communities. The prerequisites are structural: the existing slab must be sound, drain correctly, and leave workable elevations at the doors, coping, and cage track once the stone&rsquo;s thickness is added. We verify all of it with a level and a straightedge before quoting. When the slab qualifies, you get an estate-grade stone deck in days without demolition dumpsters in the driveway; when it doesn&rsquo;t, we tell you why, show you the readings, and price the rebuild honestly."),
            ("What does a travertine pool deck cost versus alternatives?",
             "Installed in our market: travertine $22&ndash;$35 per square foot; marble $26&ndash;$38; shellstone $20&ndash;$30; porcelain $18&ndash;$30; premium concrete pavers $15&ndash;$26; and cool-coat concrete resurfacing &mdash; the budget path &mdash; $6&ndash;$10. A typical 800-square-foot pool surround in travertine lands between $17,500 and $28,000. Those are wide honest ranges because coping, drains, and cage details move the number; the written proposal pins yours precisely, line by line."),
        ],
        "not_included": "We do not build or modify pool shells, waterline tile, or screen enclosures &mdash; the deck, coping, and surrounds are ours; the pool itself belongs to your pool contractor.",
    },
    "paver-sealing-repair": {
        "name": "Paver Sealing, Cleaning &amp; Repair",
        "slug": "paver-sealing-repair",
        "short": "Paver Sealing &amp; Repair",
        "h1_phrase": "Paver Sealing, Cleaning &amp; Repair",
        "numeral": "11",
        "group": "Pavers &amp; Travertine",
        "answer_block": "Paver restoration in the Orlando area runs <strong>$1.50&ndash;$3.50 per square foot</strong> for clean-sand-seal service and <strong>$8&ndash;$18 per square foot</strong> for lift-and-relay repairs of settled sections. A typical driveway restoration completes in one to two days and resets the maintenance clock for two to four years.",
        "intro_lead": "Professional cleaning, polymeric re-sanding, sealing, and lift-and-relay repair &mdash; the maintenance cycle that keeps a paver investment looking like the day it was laid.",
        "craft_p1": "Pavers are the rare surface designed to be maintained rather than replaced &mdash; but the maintenance is a system, not a pressure washer. The full restoration runs in strict order: <strong>clean</strong> (surface wash plus targeted treatment for rust, oil, tannin, and the black mold-mildew film Florida shade grows), <strong>kill and clear</strong> the joint weeds at the root, <strong>re-sand</strong> with polymeric sand driven fully into the joints and activated with a controlled wetting, and <strong>seal</strong> with the finish you choose &mdash; invisible natural, color-enriching enhanced, or glossy wet-look. Skip a step and the result betrays you: sand without cleaning locks the stains in; sealer without sand glues a failing joint structure in place; a rental pressure washer alone blasts the joints empty and starts the decline it meant to stop.",
        "craft_p2": "Repair is the other half of the service, and it is where pavers repay their higher install cost. <strong>Settled sections</strong> &mdash; the dip at the driveway apron, the low spot where the downspout discharges &mdash; lift out, get their base rebuilt and compacted, and relay with the same stones, invisibly. <strong>Broken or stained pavers</strong> swap individually from attic stock or matched product. <strong>Spreading edges</strong> get real concrete restraint retrofitted where the original installer skipped it. This is also where we serve owners whose pavers we didn&rsquo;t install: the crews that laid half of west Orlando&rsquo;s pavers in the boom years are gone, and their shortcuts are surfacing. We diagnose them honestly, fix what is fixable, and tell you plainly when a field is too far gone to rescue &mdash; with the rebuild number beside the repair number so you choose with facts.",
        "scope_items": [
            "Deep cleaning &mdash; pressure wash &amp; targeted stain treatment",
            "Rust, oil, tannin &amp; efflorescence removal",
            "Mold, mildew &amp; algae remediation",
            "Weed &amp; ant-colony joint clearing",
            "Polymeric re-sanding, compacted &amp; activated",
            "Sealing: natural, enhanced &amp; wet-look finishes",
            "Slip-additive sealing for pool decks",
            "Lift-and-relay repair of settled sections",
            "Individual paver replacement &amp; color matching",
            "Edge-restraint retrofit on spreading fields",
            "Re-leveling at aprons, downspouts &amp; drains",
            "Travertine &amp; natural-stone cleaning with stone-safe chemistry",
            "Maintenance-cycle scheduling &amp; reminders",
        ],
        "options_rows": [
            ("Natural finish sealer", "Purists &amp; matte architecture", "Protection with zero shine"),
            ("Enhanced (color-boost)", "Faded fields, rich blends", "Deepens tone like a wet stone"),
            ("Wet-look gloss", "Statement drives &amp; decks", "Maximum depth &amp; sheen"),
            ("Lift &amp; relay", "Settled or trenched sections", "Same stones, rebuilt base, invisible"),
        ],
        "pricing_rows": [
            ("Clean, re-sand &amp; seal (full cycle)", "$1.50&ndash;$3.50 / sq ft", "The complete restoration"),
            ("Cleaning &amp; stain treatment only", "$0.60&ndash;$1.50 / sq ft", "Wash + targeted protocols"),
            ("Polymeric re-sanding only", "$0.75&ndash;$1.75 / sq ft", "Joints cleared, filled &amp; activated"),
            ("Lift-and-relay repair", "$8&ndash;$18 / sq ft", "Base rebuilt, same stones"),
            ("Individual paver replacement", "$15&ndash;$40 / paver", "From stock or matched"),
            ("Edge-restraint retrofit", "$9&ndash;$16 / linear ft", "Stops field migration"),
            ("Stone-deck cleaning &amp; sealing", "$2&ndash;$4 / sq ft", "Travertine-safe chemistry"),
        ],
        "faqs": [
            ("How often should pavers be sealed and re-sanded in Florida?",
             "On average, every two to four years &mdash; toward two for full-sun driveways and pool decks that live under sprinklers and storms, toward four for shaded, low-traffic patios. The honest indicator isn&rsquo;t the calendar; it&rsquo;s the joints and the water. When joint sand sits noticeably low, when weeds germinate in the lines, or when rain stops beading and starts soaking dark, the protection has run its course. We log every job&rsquo;s date and send a reminder when your surface enters the window &mdash; the difference between maintenance and restoration is usually eighteen ignored months."),
            ("My pavers look terrible &mdash; black stains, weeds, sunken spots. Rescue or replace?",
             "Usually rescue, and the transformation surprises people. The black film is organic growth, not damage &mdash; it strips off with the right chemistry. Weeds live in the joints, not under the field &mdash; they clear and stay cleared once fresh polymeric sand locks the lines. Sunken spots are base failures, but local ones &mdash; they lift and relay invisibly. The full sequence typically runs $1.50&ndash;$3.50 per square foot plus repairs, against $14-plus to rebuild &mdash; a fraction of the cost for ninety percent of the day-one look. The exception is a field failing everywhere at once on a never-compacted base; we&rsquo;ll recognize it during the walk-through, tell you straight, and quote both paths."),
            ("What does polymeric sand actually do?",
             "Three jobs at once. Structurally, it locks the pavers into a single interlocked mat, so loads spread across the field instead of rocking individual stones. Defensively, it hardens against rain, denying weeds a seedbed and ants a highway &mdash; the two invasions every Florida paver owner knows. And aesthetically, it keeps the joint lines crisp instead of scattered across the surface. The activation step is where amateur jobs fail: too little water and the sand never sets; too much and it foams into a haze across the face. We meter it &mdash; and the difference lasts for years."),
            ("Should new pavers be sealed right away?",
             "Give a brand-new field sixty to ninety days first &mdash; new concrete pavers need to breathe out efflorescence (the natural white mineral bloom) before sealing, or you lock the haze under the finish. After that window, sealing early in the surface&rsquo;s life is the best money in paver ownership: it slows UV fading before it starts, makes every future cleaning easier, and hardens the joints from year one. On new installs we schedule the first sealing as a return visit at the right date, so the timing is engineered rather than remembered."),
            ("Do you clean and seal travertine and natural stone too?",
             "Yes &mdash; with different chemistry, and the difference matters. The acids and aggressive surfactants that safely brighten concrete pavers will etch and dull natural stone; travertine wants pH-neutral cleaners, gentler pressure, and a breathable penetrating sealer that protects the pores without plugging them. It is the same reason we install stone decks with stone-specific products: the material rewards you for decades, but only if every product that touches it was chosen for it. If someone quotes one process for your pavers and your travertine, they are planning to use the wrong one on something."),
        ],
        "not_included": "We restore pavers and natural stone &mdash; we do not paint, epoxy-coat, or resurface pavers with cementitious products. If a field is past honest restoration, we say so and quote its rebuild.",
    },
    "driveway-extensions": {
        "name": "Driveway Extensions &amp; Parking Solutions",
        "slug": "driveway-extensions",
        "short": "Driveway Extensions",
        "h1_phrase": "Driveway Extensions &amp; Widening",
        "numeral": "12",
        "group": "Pavers &amp; Travertine",
        "answer_block": "Driveway widening in the Windermere and Orlando area runs <strong>$10&ndash;$16 per square foot</strong> in concrete and <strong>$15&ndash;$25</strong> in pavers. A typical 3-to-4-foot widening strip or a golf-cart / third-car pad completes in two to four site days &mdash; HOA submittal support included.",
        "intro_lead": "Widening strips, third-car pads, golf-cart paths, and permeable parking &mdash; fixing the one thing almost every Central Florida builder undersized: the driveway.",
        "craft_p1": "Walk any street built in the last fifteen years from Horizon West to St. Cloud and you&rsquo;ll see the same scene: two SUVs shingled onto a driveway platted for one and a half, a third car with two tires in the St. Augustine, trash bins living where a car should. Builders pour the code minimum because every square foot saved multiplies across four hundred lots; homeowners inherit the shortage. Extensions are our answer, engineered like first-class work rather than an afterthought: the addition excavated and based to the same depth as a new drive, <strong>doweled into the existing slab</strong> (concrete) or <strong>interlocked into a retrofit edge system</strong> (pavers), with falls that keep the new surface draining to the swale &mdash; not into the garage, and never onto the neighbor.",
        "craft_p2": "The formats cover how west Orlando actually parks. <strong>Widening strips</strong> of two to four feet turn a shingle-park driveway into a true two-car. <strong>Third-car and guest pads</strong> give the teenager&rsquo;s car or the visiting in-laws a home that isn&rsquo;t the lawn. <strong>Golf-cart paths and pads</strong> &mdash; increasingly the second vehicle in Windermere, Celebration, and the golf communities &mdash; connect garage to street with a surface that shrugs off the daily roll. <strong>Permeable turf-and-paver systems</strong> add parking where drainage rules or lot coverage limits say solid surface can&rsquo;t go. And because visible driveway changes trip ARC review in most of our communities, every extension proposal ships with the submittal documentation ready &mdash; matching material specs, dimensions, and the drainage note that gets approvals through clean.",
        "scope_items": [
            "Driveway widening strips (2&ndash;4 ft, matched finish)",
            "Third-car &amp; guest parking pads",
            "Golf-cart paths, pads &amp; garage aprons",
            "Circular-drive additions &amp; turnouts",
            "Permeable turf-paver &amp; open-grid parking",
            "Gravel-stabilization grid systems",
            "Doweled concrete tie-ins to existing slabs",
            "Paver interlock &amp; retrofit edge restraint",
            "Drainage-neutral grading to the existing swale",
            "Trash-bin &amp; equipment pads screened from street",
            "County right-of-way &amp; apron coordination",
            "ARC / HOA submittal package included",
        ],
        "options_rows": [
            ("Concrete widening strip", "Matching existing concrete drives", "Doweled, jointed &amp; finish-matched"),
            ("Paver extension", "Paver drives &amp; upgrade-minded owners", "Interlocked field, invisible seam"),
            ("Permeable / turf grid", "Coverage-limited or soggy lots", "Parking that still drains"),
            ("Golf-cart pad &amp; path", "Golf &amp; trail communities", "The second vehicle&rsquo;s garage"),
        ],
        "pricing_rows": [
            ("Concrete widening strip", "$10&ndash;$16 / sq ft", "Doweled &amp; finish-matched"),
            ("Paver widening / extension", "$15&ndash;$25 / sq ft", "Interlocked, edge-restrained"),
            ("Third-car / guest pad", "$2,200&ndash;$6,500", "Typical 9&times;20 to 12&times;24"),
            ("Golf-cart path or pad", "$1,200&ndash;$4,000", "Surface &amp; route dependent"),
            ("Permeable turf-paver parking", "$14&ndash;$24 / sq ft", "Grid, base &amp; fill"),
            ("Circular-drive addition", "Quoted by layout", "Radius &amp; apron engineering"),
            ("Apron / right-of-way tie-in", "$900&ndash;$2,800", "To jurisdiction standard"),
        ],
        "faqs": [
            ("Will the HOA approve a driveway extension?",
             "In most west Orange communities, yes &mdash; widening is among the most commonly approved hardscape requests, because boards would rather see cars on pavement than on grass. Approval hinges on the package: matching material and finish, dimensions inside the community&rsquo;s coverage rules, and a drainage note showing the addition sheds to your swale rather than a neighbor&rsquo;s lot. We prepare exactly that package with every extension proposal. The requests that get denied are the ones that surprise the committee &mdash; unmatched materials, lot-line-to-lot-line concrete, no drainage answer. Ours don&rsquo;t surprise them."),
            ("Will the extension match my existing driveway?",
             "In pavers &mdash; yes, effectively invisibly: we identify your existing product and blend (or its closest current successor), tooth the new field into the old, and the seam disappears. In concrete &mdash; honestly, almost: new concrete beside weathered concrete reads slightly lighter for the first year or two and converges as it ages; we minimize the contrast by matching finish texture and joint pattern so the addition reads intentional. If perfect uniformity matters most, that is a genuine argument for either a paver extension or &mdash; on an aging drive &mdash; replacing the whole surface at once; we&rsquo;ll price the options side by side."),
            ("Can I add parking without creating a drainage problem?",
             "Yes &mdash; it just has to be designed, because every new square foot of pavement is rain that stops soaking and starts flowing. We grade extensions to carry water to your lot&rsquo;s existing drainage path, and where the lot is already working hard &mdash; or where community coverage limits cap solid surface &mdash; we build <strong>permeable systems</strong>: open-grid pavers or turf-reinforcement grids that hold a parked car while rain passes straight through. They are the answer for soggy side yards, coverage-capped lots, and any community where the drainage note is the difference between approval and denial."),
            ("What about a pad for the golf cart, boat, or trash bins?",
             "All three are everyday builds for us. Golf-cart pads and connector paths get a smooth, rolled-friendly surface from garage to street. Boat and trailer pads step up in thickness and base depth to carry the tongue-weight point loads &mdash; tell us the rig honestly and we engineer to it. Bin pads are the humble hero: a modest slab or paver pad, usually screened behind the gate line, that gets the cans off the driveway and ends the Tuesday shuffle. Small scopes, same standard &mdash; each one bases, drains, and finishes like our full driveways, because callbacks don&rsquo;t care how small the pour was."),
            ("What does driveway widening cost in the Orlando area?",
             "Concrete widening runs $10&ndash;$16 per square foot; paver extensions $15&ndash;$25. A three-foot strip down one side of a typical drive lands between $1,800 and $3,600; a full third-car pad between $2,200 and $6,500; golf-cart work $1,200&ndash;$4,000. Permeable systems price at $14&ndash;$24 per square foot where drainage or coverage rules apply. Every number itemizes on the written proposal &mdash; and extensions phase beautifully if you want the widening now and the guest pad next season."),
        ],
        "not_included": "We do not pave public streets or build structural bridges over drainage systems &mdash; residential extensions, pads, and paths tied to your existing driveway are the scope.",
    },
}
