# Windermere Concrete — service data (part 1 of 4): driveways, patios, pool decks.
# Copy is 100% original to this brand (zero overlap with sister sites).
SERVICES = {
    "concrete-driveways": {
        "name": "Concrete Driveways",
        "slug": "concrete-driveways",
        "short": "Concrete Driveways",
        "h1_phrase": "Concrete Driveways",
        "numeral": "01",
        "group": "Concrete",
        "answer_block": "A new concrete driveway in the Windermere and west Orlando area typically runs <strong>$9&ndash;$14 per square foot installed</strong> for a standard broom finish, and <strong>$16&ndash;$26</strong> for stamped or decorative work. Most residential driveways are demolished, re-based, poured, and jointed within three to five working days, plus cure time.",
        "intro_lead": "Estate-grade poured driveways for Central Florida &mdash; engineered bases, disciplined joint layouts, and finishes chosen to complement the home, from crisp broom-finish to architectural exposed aggregate.",
        "craft_p1": "The driveway is the first surface a guest touches at your home and the last one most contractors think carefully about. In our market &mdash; Windermere&rsquo;s sand streets, Dr. Phillips&rsquo; oak canopies, Horizon West&rsquo;s engineered lots &mdash; the difference between a driveway that stays flat for twenty-five years and one that spider-cracks by its third summer is decided before any concrete arrives: in the probing of the subgrade, the lifts of compacted rock beneath, and a joint plan drawn to the slab&rsquo;s actual geometry. Under <strong>the Windermere Craft Code</strong>, all forty-eight checkpoints apply to every driveway we build, and the base work gets photographed before it disappears &mdash; you keep the evidence.",
        "craft_p2": "Design range matters as much as durability here. We pour classic broom-finish in warm gray and buff tones, architectural <strong>exposed aggregate</strong> that reads like washed river stone, and <strong>bordered fields</strong> &mdash; a smooth or stamped band framing a textured center &mdash; that satisfy the most demanding ARC palettes. Circular and motor-court layouts are a specialty: radius forming, consistent falls across compound curves, and joint patterns that follow the geometry instead of fighting it. Every proposal spells out mix strength, slab thickness, reinforcement, and joint spacing in writing, so you can compare our scope line-for-line against any other bid &mdash; and see exactly what the cheaper number leaves out.",
        "scope_items": [
            "New driveway pours &mdash; standard, circular &amp; motor-court layouts",
            "Complete tear-out, haul-away &amp; replacement of failed driveways",
            "Subgrade probing, soft-spot correction &amp; structural fill",
            "Crushed-rock base placed and compacted in measured lifts",
            "Fiber, wire, or rebar reinforcement per the written spec",
            "Saw-cut control joints on an engineered layout",
            "Isolation joints at the garage, sidewalk &amp; apron",
            "Exposed-aggregate &amp; bordered decorative finishes",
            "Integral color matched to ARC-approved palettes",
            "Thickened edges &amp; turnout aprons for heavy vehicles",
            "County right-of-way apron tie-ins",
            "Penetrating siloxane sealing",
            "ARC / HOA sample boards &amp; submittal documentation",
            "Same-day site cleanup with washout containment",
        ],
        "options_rows": [
            ("Broom finish", "Everyday driveways; best grip-to-cost ratio", "The Central Florida workhorse &mdash; clean, honest, ARC-safe"),
            ("Exposed aggregate", "Estate frontages; hides tire marks", "Washed-stone texture with serious curb presence"),
            ("Bordered field", "ARC communities wanting definition", "Stamped or smooth border framing a broom field"),
            ("Integral color", "Matching house &amp; palette", "Color through the full slab depth &mdash; never painted on"),
        ],
        "pricing_rows": [
            ("Broom-finish driveway (4&Prime; reinforced)", "$9&ndash;$14 / sq ft", "Installed, jointed &amp; cured"),
            ("Tear-out &amp; full replacement", "$12&ndash;$17 / sq ft", "Demolition &amp; haul-away included"),
            ("Exposed-aggregate finish", "$14&ndash;$20 / sq ft", "Washed-stone architectural texture"),
            ("Stamped / bordered decorative", "$16&ndash;$26 / sq ft", "Pattern, color &amp; sealer included"),
            ("Circular / motor-court layout", "$13&ndash;$22 / sq ft", "Radius forming &amp; compound falls"),
            ("Integral color", "+$1.75&ndash;$4 / sq ft", "Full-depth color, sample-matched"),
            ("Subgrade correction (where needed)", "$2.50&ndash;$6 / sq ft", "Soft-soil cutout &amp; structural fill"),
            ("Penetrating sealer", "$1&ndash;$2 / sq ft", "UV &amp; stain protection"),
        ],
        "faqs": [
            ("How long does a new concrete driveway last in Central Florida?",
             "Built correctly, twenty-five to forty years. The qualifier is the entire answer. Florida driveways rarely die of old age &mdash; they die of skipped base compaction, missing control joints, and slabs poured thin to win a bid. Our approach attacks each failure mode by name: the subgrade is probed and corrected, the rock base goes in compacted lifts, reinforcement is chaired mid-slab, and joints are cut on an engineered layout within the correct window. That is also why our proposal lists thickness, PSI, and joint spacing in writing &mdash; so the driveway you were quoted is provably the driveway you got."),
            ("When can we drive on the new slab?",
             "Walk on it after twenty-four hours; park on it after seven days; give it a full month before the heaviest thing you own touches it. Concrete reaches roughly three-quarters of its design strength in the first week and keeps hardening for weeks after. We leave a printed cure calendar at handover with the exact dates for your pour, so nobody in the household has to guess."),
            ("Will the new driveway crack?",
             "Concrete shrinks as it cures &mdash; that is chemistry, not workmanship. What workmanship controls is where the shrinkage relieves itself. We saw control joints on an engineered grid so the slab cracks inside the joint, invisibly, instead of wandering across the field. A hairline inside a joint is the system working. A random diagonal crack, a heaved corner, or a settled panel is a base or joint failure &mdash; the exact defects the Craft Code&rsquo;s pre-pour checkpoints exist to prevent, and the reason our workmanship warranty is in writing."),
            ("Do you handle the HOA or ARC approval for a new driveway?",
             "We prepare the package for you &mdash; and in communities like Keene&rsquo;s Pointe, Windsong, or the Horizon West villages, that package is the difference between one review cycle and three. Your proposal comes with the color and finish sample documentation, dimensions, and drawings most architectural committees ask for. You submit it (or your manager does), and we build precisely what was approved. What we never do is start work ahead of the approval; a driveway poured before the letter arrives is a driveway you can be ordered to remove."),
            ("Can you widen my existing driveway instead of replacing it?",
             "Often, yes &mdash; and it is one of the smartest spends in the newer communities, where builders poured the code-minimum width and two SUVs simply don&rsquo;t fit. We excavate and base the addition to the same standard as a full pour, pin it to the existing slab with doweled connections, and match the finish as closely as cured-versus-new concrete allows. We are honest about the one thing nobody can promise: brand-new concrete beside weathered concrete shows a tone difference at first and blends as it ages. If the mismatch would bother you, we&rsquo;ll price the full replacement so you can decide with both numbers in hand."),
            ("How much does a concrete driveway cost in the Windermere area?",
             "For most homes: broom finish runs $9&ndash;$14 per square foot installed; tear-out-and-replace $12&ndash;$17; decorative and stamped work $16&ndash;$26. A typical 600-square-foot two-car driveway lands between $5,500 and $10,000 depending on finish and what the demolition uncovers. Larger motor courts and circular drives price by layout. Those are real ranges, printed here on purpose &mdash; and your written proposal breaks the exact number into line items you can question."),
        ],
        "not_included": "We do not pour structural or load-bearing slabs, house foundations, or public roadwork. Driveways, aprons, and the flatwork around them are the craft we practice daily.",
    },
    "concrete-patios": {
        "name": "Concrete Patios",
        "slug": "concrete-patios",
        "short": "Concrete Patios",
        "h1_phrase": "Concrete Patios",
        "numeral": "02",
        "group": "Concrete",
        "answer_block": "A poured concrete patio in west Orlando typically costs <strong>$8&ndash;$13 per square foot installed</strong> for broom finish and <strong>$15&ndash;$24</strong> for stamped or decorative finishes. A 300-square-foot patio usually forms, pours, and cures over roughly a week &mdash; slope, joints, and drainage included, not extra.",
        "intro_lead": "Outdoor-living slabs designed around how you actually entertain &mdash; poured with deliberate falls, layout-matched joints, and finishes that stay comfortable through a Florida summer.",
        "craft_p1": "A patio is the room your Florida house was missing, and it fails or succeeds on decisions made at the drawing stage. The first is <strong>drainage</strong>: our afternoon storms drop an inch of water in an hour, and a slab without a designed fall sends that water toward the one place it must never go &mdash; your slab edge and stem wall. Every patio we pour carries a deliberate pitch away from the house and the pool cage, and we hose-test it at handover while you watch. The second is <strong>scale</strong>: we lay out the footprint around your actual furniture and traffic paths, staked and strung on the ground for your sign-off, because a patio one dining chair too small is a mistake you live with for decades.",
        "craft_p2": "Finish is where a patio becomes architecture. Broom finish remains the honest budget choice &mdash; grippy, cool-toned, ARC-safe. <strong>Stamped textures</strong> in slate, flagstone, and wood-plank patterns bring stone character at a fraction of natural-stone labor, colored integrally and sealed against UV so the tone survives the sun. For renovations, <strong>decorative overlays</strong> resurface a sound-but-tired slab without demolition. And because patios anchor bigger outdoor plans, we form and pour the supporting cast in the same mobilization: fire-pit rings, grill pads, step transitions, and the connecting walks that tie it all back to the house. Everything on one proposal, one crew, one warranty.",
        "scope_items": [
            "New patio slabs &mdash; broom, stamped, or exposed-aggregate finish",
            "Patio extensions doweled into existing slabs",
            "Stamped textures: slate, flagstone, ashlar &amp; wood plank",
            "Integral color &amp; antiquing release, sample-matched",
            "Decorative overlays on structurally sound slabs",
            "Engineered falls &mdash; hose-tested drainage at handover",
            "Screened-lanai &amp; pool-cage slab preparation",
            "Fire-pit rings, grill pads &amp; kitchen footings (non-structural)",
            "Steps, landings &amp; grade transitions",
            "Connecting walkways to pool, drive &amp; entries",
            "Layout-matched saw-cut control joints",
            "Isolation joints at the house &amp; fixed structures",
            "UV-stable decorative sealing",
            "ARC / HOA documentation where required",
        ],
        "options_rows": [
            ("Broom finish", "Lanais, everyday family patios", "Grippy, cool-toned, budget-honest"),
            ("Stamped slate / flagstone", "Outdoor rooms with stone character", "Integral color + release, UV-sealed"),
            ("Wood-plank stamp", "Modern &amp; farmhouse architecture", "Plank texture without the rot"),
            ("Decorative overlay", "Sound but dated existing slabs", "New face, no demolition"),
        ],
        "pricing_rows": [
            ("Broom-finish patio slab", "$8&ndash;$13 / sq ft", "Reinforced, sloped &amp; jointed"),
            ("Stamped decorative patio", "$15&ndash;$24 / sq ft", "Pattern, color &amp; sealer included"),
            ("Decorative overlay (existing slab)", "$9&ndash;$16 / sq ft", "Surface prep included"),
            ("Patio extension (doweled)", "$9&ndash;$14 / sq ft", "Tied to the existing slab"),
            ("Steps &amp; landings", "$300&ndash;$900 each", "Formed &amp; finished to match"),
            ("Fire-pit ring / grill pad", "$700&ndash;$1,800", "Sized to the equipment"),
            ("Connecting walkway", "$9&ndash;$15 / sq ft", "Matched finish &amp; joints"),
            ("UV-stable sealer", "$1&ndash;$2.25 / sq ft", "Protects stamp &amp; color"),
        ],
        "faqs": [
            ("What size should we build?",
             "Start from the furniture, not the budget. A café table and two chairs live comfortably in 10&times;10; a true dining-plus-lounge outdoor room wants 16&times;20 or better; an outdoor kitchen adds a working zone beyond that. Before we form anything we stake and string the exact footprint on your grass so you can walk it, place chairs on it, and feel the size in person &mdash; the fifteen-minute step that prevents the most common patio regret, which is always &lsquo;we should have gone two feet bigger.&rsquo;"),
            ("Stamped concrete or pavers for a patio &mdash; what would you honestly pick?",
             "We install both, so the answer is criteria, not preference. Pick stamped concrete when you want a continuous, weed-proof surface with stone character at a lower installed cost, and you accept that any future repair means color-matching a patch. Pick pavers when you want the ability to lift and relay a section invisibly &mdash; after root movement or a utility trench &mdash; and you accept joint maintenance every few years. On tight-access lots where a mixer can&rsquo;t reach, pavers win by logistics. We will tell you which side your specific yard lands on during the consultation, and we genuinely do not care which one you choose &mdash; we warranty both."),
            ("Does a concrete patio get too hot for bare feet?",
             "A dark, smooth slab in full sun does; a well-chosen one doesn&rsquo;t. Surface temperature is set by three choices we make together: color (lighter integral tones reflect meaningfully more heat), texture (broomed and stamped surfaces carry less contact area than steel-troweled ones), and shade planning around where the afternoon sun actually lands on your lot. If barefoot comfort is the priority &mdash; usually around pools &mdash; we will also show you the honest comparison against travertine and pavers, which run cooler by nature, so you pick with the full picture."),
            ("Can you resurface our existing patio instead of tearing it out?",
             "If the slab under it is structurally sound &mdash; yes, and it saves real money. A decorative overlay bonds a new wearing surface over sound concrete: stamped, colored, or smooth. The gate is the word <em>sound</em>. Stains, dullness, and surface scaling are overlay candidates; through-cracks, heaving, and settlement are not, because an overlay over movement just prints the same crack in a new color within a year. We check the slab for deflection and drainage before quoting either path, and we will not sell you an overlay your slab doesn&rsquo;t qualify for."),
            ("How disruptive is the build, and how long until we can use it?",
             "A typical patio runs about a week of site time: a day of layout and excavation, a day of base and forming, the pour day, then joint cutting and &mdash; for decorative work &mdash; a day or two of color and seal. You can walk the slab after a day; give it a week before furniture and heavy planters. We keep the site contained as we go: forms pulled, washout contained, debris gone the same day it&rsquo;s created. The precise schedule for your scope is printed in the proposal."),
            ("What does a concrete patio cost in the Orlando area?",
             "Broom finish runs $8&ndash;$13 per square foot installed; stamped decorative $15&ndash;$24; overlays on sound slabs $9&ndash;$16. A 300-square-foot broom patio typically lands between $2,400 and $3,900; the same footprint stamped, $4,500&ndash;$7,200. Steps, fire-pit rings, and connecting walks price as line items you can add or cut. The ranges are published here so you can budget before we ever meet &mdash; the written proposal turns them into one exact number."),
        ],
        "not_included": "We do not build roofed structures, pergolas, or outdoor-kitchen enclosures &mdash; we pour the slabs, footings pads, and hardscape they stand on, and coordinate cleanly with your builder.",
    },
    "concrete-pool-decks": {
        "name": "Concrete Pool Decks",
        "slug": "concrete-pool-decks",
        "short": "Concrete Pool Decks",
        "h1_phrase": "Concrete Pool Decks",
        "numeral": "03",
        "group": "Concrete",
        "answer_block": "A concrete pool deck in the Windermere area runs <strong>$9&ndash;$14 per square foot</strong> for a new slip-textured pour and <strong>$6&ndash;$10</strong> for cool-coat acrylic resurfacing of a sound existing deck. Every deck we build drains away from the coping and the cage track &mdash; verified with a hose test at handover.",
        "intro_lead": "Slip-textured, heat-conscious pool surrounds &mdash; new pours, Kool-Deck-style acrylic resurfacing, and stamped finishes engineered to live wet, barefoot, and in full Florida sun.",
        "craft_p1": "A pool deck carries the toughest brief in residential concrete: grip when soaked, comfort under bare feet at 2 p.m. in July, and indifference to a constant bath of chlorinated or salt water. Every choice runs through those three filters. Texture comes first &mdash; we finish decks in broomed, stamped, or knock-down acrylic surfaces that grip wet skin, never the slick steel-trowel finish that turns a deck into a liability. Temperature comes second: lighter integral colors and acrylic <strong>cool-coat systems</strong> measurably drop surface heat, and we&rsquo;ll tell you plainly which finishes to avoid if barefoot comfort matters to your family. Chemistry comes third: UV-stable, chlorine-tolerant sealers, reapplied on a maintenance cycle we put in writing.",
        "craft_p2": "The invisible engineering matters even more around water. The deck, the pool shell, and the screen-cage footer are three structures that move independently &mdash; pour them tight together and the deck cracks at the coping line, the most visible seam on the property. We isolate all three with proper joints, pitch every panel away from the coping and the cage track, and confirm the water&rsquo;s path with a hose before we leave. For renovations, our <strong>Kool-Deck-style acrylic resurfacing</strong> renews a sound but dated deck without demolition: cracks routed and repaired, spalling ground out, then a fresh knock-down texture in the color you choose. It is the highest-value pool-deck spend in Central Florida, and we quote it honestly against replacement so you can see both numbers.",
        "scope_items": [
            "New pool-deck pours with slip-rated textures",
            "Kool-Deck-style acrylic knock-down resurfacing",
            "Stamped stone, slate &amp; shell textures (non-slip)",
            "Cool-coat acrylic systems for barefoot comfort",
            "Integral color in heat-reflective tones",
            "Isolation joints at shell, coping &amp; cage footer",
            "Engineered falls away from coping &amp; cage track",
            "Crack routing, spall repair &amp; slab preparation",
            "Deck extensions &amp; sun-shelf surrounds",
            "Coping transitions &amp; retrofit detailing",
            "Connecting walkways to lanai &amp; house",
            "UV-stable, chlorine-tolerant sealing",
            "Hose-tested drainage at the walkthrough",
            "ARC / HOA color documentation where required",
        ],
        "options_rows": [
            ("Cool-coat acrylic", "Renovating sound decks; hottest exposures", "Knock-down texture, coolest underfoot"),
            ("Broom / textured pour", "New construction on a budget", "Honest grip, lighter tones run cooler"),
            ("Stamped stone / shell", "Design-led decks", "Non-slip textures, sealed for chemistry"),
            ("Stamped border + textured field", "Balance of budget &amp; character", "Definition without full-field cost"),
        ],
        "pricing_rows": [
            ("New textured pool-deck pour", "$9&ndash;$14 / sq ft", "Reinforced, isolated &amp; sloped"),
            ("Cool-coat acrylic resurfacing", "$6&ndash;$10 / sq ft", "Over structurally sound decks"),
            ("Stamped decorative deck", "$16&ndash;$25 / sq ft", "Non-slip pattern, color &amp; sealer"),
            ("Border + field combination", "$13&ndash;$19 / sq ft", "Stamped frame, textured center"),
            ("Crack &amp; spall repair (pre-resurface)", "$9&ndash;$22 / linear ft", "Routed, filled &amp; ground"),
            ("Deck extension", "$10&ndash;$15 / sq ft", "Doweled &amp; isolation-jointed"),
            ("Chlorine-tolerant sealer", "$1.25&ndash;$2.50 / sq ft", "Reapply every 2&ndash;3 years"),
            ("Connecting walkway", "$9&ndash;$15 / sq ft", "Matched texture &amp; falls"),
        ],
        "faqs": [
            ("What actually keeps a pool deck cool enough to walk on?",
             "Color and system, in that order. A light integral tone reflects a large share of solar load that a charcoal surface absorbs; an acrylic cool-coat adds a texture whose peaks carry your weight while the valleys stay off your skin, which is why the classic Florida knock-down deck reads dramatically cooler than a bare slab. What does not work is wishing &mdash; a dark stamped deck in full western sun will be hot no matter whose name is on the truck. We will tell you that before you choose it, and show you the travertine comparison if barefoot temperature is your deciding factor."),
            ("Our deck is cracked and dated. Resurface or replace?",
             "Put a straightedge and a hose on it &mdash; that is essentially what we do. If the slab is flat, drains correctly, and the cracks are stable hairlines, resurfacing wins by thousands: we route and fill the cracks, grind the spalling, and float a fresh acrylic system over the top. If panels have settled, water ponds against the coping, or cracks are wide and moving seasonally, resurfacing is cosmetics over a structural problem and we will not sell it to you. Roughly speaking, resurfacing runs $6&ndash;$10 per square foot against $12&ndash;$17 to demolish and repour &mdash; we quote both when the slab is borderline so the decision is yours with real numbers."),
            ("Why does the deck have to be separated from the pool and the cage?",
             "Because Florida ground moves seasonally and the three structures ride it differently. The pool shell is anchored deep, the cage footer is anchored shallow, and the deck floats between them; joined rigidly, the deck loses that argument every time, cracking right at the coping or the cage track. Isolation joints let each element move without dragging the others &mdash; an invisible detail that adds nothing to the photos and everything to year five. Its absence is the single most common defect we find in decks we&rsquo;re called to fix."),
            ("Will salt-system water and chlorine damage the finish?",
             "Unsealed, yes &mdash; pool chemistry etches and pits raw concrete slowly but relentlessly, and salt systems accelerate the surface scaling. The defense is a sealer specified for pool exposure: UV-stable so it doesn&rsquo;t yellow, breathable so it doesn&rsquo;t trap moisture, and slip-rated so protection doesn&rsquo;t cost you grip. Plan on reapplication every two to three years; we note the due date in your care guide and can put you on a reminder cycle so it actually happens."),
            ("Can you work around our screen enclosure?",
             "Yes, and carefully &mdash; the cage is usually the most expensive thing standing on the deck. Where a resurface runs to the cage track we mask and detail around the anchors; where a replacement requires work under the track we coordinate the sequence with your enclosure contractor so panels and doors go undisturbed. What we never do is jack, cut, or &lsquo;temporarily support&rsquo; a cage ourselves &mdash; that is enclosure-contractor work, and pretending otherwise is how decks end up cheap and cages end up condemned."),
            ("What does pool-deck work cost in the Windermere area?",
             "Cool-coat acrylic resurfacing: $6&ndash;$10 per square foot. New textured pours: $9&ndash;$14. Stamped decorative decks: $16&ndash;$25. A typical 700-square-foot deck resurfaces for $4,200&ndash;$7,000 or rebuilds for $6,300&ndash;$9,800 &mdash; the honest fork in the road we quote side-by-side when your slab is a candidate for either. Repairs, extensions, and sealing price as line items on the written proposal."),
        ],
        "not_included": "We do not build or repair pool shells, coping stone, or screen enclosures &mdash; we build the deck around them and coordinate with your pool and enclosure contractors when scopes meet.",
    },
}
