# Windermere Concrete — service data (part 2 of 4): stamped, slabs, repair/resurfacing.
SERVICES = {
    "stamped-concrete": {
        "name": "Stamped &amp; Decorative Concrete",
        "slug": "stamped-concrete",
        "short": "Stamped Concrete",
        "h1_phrase": "Stamped &amp; Decorative Concrete",
        "numeral": "04",
        "group": "Concrete",
        "answer_block": "Stamped concrete in the Windermere and Orlando area runs <strong>$15&ndash;$26 per square foot installed</strong> depending on pattern, color system, and site. It delivers the look of slate, travertine, or flagstone at roughly half to two-thirds of natural stone&rsquo;s installed cost &mdash; one continuous, weed-free surface.",
        "intro_lead": "Slate, flagstone, ashlar, and wood-plank textures pressed into fresh concrete &mdash; integrally colored, antiqued, and UV-sealed to keep their depth under the Florida sun.",
        "craft_p1": "Stamped concrete succeeds or embarrasses on the same three details, and all three happen during a two-hour window while the slab is deciding to harden. <strong>Timing</strong>: stamp too early and the texture smears; too late and the mats print shallow, leaving the &lsquo;faded stamp&rsquo; look you see on rushed jobs. <strong>Color layering</strong>: we color the concrete integrally &mdash; through its full depth &mdash; then antique the texture with a release in a second tone, which is what gives real stone its shadowed depth; paint-on color sitting on gray concrete is how stamped work goes wrong. <strong>Sealing</strong>: a UV-stable sealer, applied at the right cure window and renewed on schedule, is the difference between a patio that holds its color for a decade and one that chalks out in two summers.",
        "craft_p2": "Pattern discipline is a design service we take seriously in this market. An ashlar slate reads beautifully beside transitional architecture; a random flagstone suits a lakefront garden; a wood-plank stamp gives a modern farmhouse its porch without the rot. We map pattern repeat and border orientation to the space &mdash; grout lines running with the house&rsquo;s sight lines, borders framing rather than colliding &mdash; and we build an ARC-ready sample set (pattern photo, color chips, sealed test tile) for communities that review finishes. Stamped work covers patios, pool decks, driveways, walkways, and entries; wherever it goes, the slab beneath it is built to the same forty-eight-checkpoint standard as everything else we pour, because a beautiful texture on a failing slab is just an expensive crack.",
        "scope_items": [
            "Stamped patios, pool decks, driveways &amp; walkways",
            "Ashlar slate, random flagstone, cobble &amp; wood-plank patterns",
            "Integral color through the full slab depth",
            "Antiquing release &amp; secondary toning",
            "Stained &amp; dyed decorative finishes",
            "Colored broom-finish &amp; smooth-troweled accents",
            "Stamped borders &amp; soldier bands on plain fields",
            "Slip-additive sealing for wet areas",
            "Pattern &amp; color sample boards for ARC review",
            "Re-seal &amp; color-refresh of existing stamped work",
            "Layout-matched control joints hidden in grout lines",
            "UV-stable protective sealing",
        ],
        "options_rows": [
            ("Ashlar slate", "Transitional &amp; estate architecture", "The most requested pattern in west Orlando"),
            ("Random flagstone", "Garden paths, lakefront patios", "Organic joints, natural repeat"),
            ("Wood plank", "Modern farmhouse, porches", "Grain texture, zero rot or splinters"),
            ("Cobble / brick-course", "Drives, aprons &amp; borders", "Old-world texture that passes ARC"),
        ],
        "pricing_rows": [
            ("Stamped patio or walkway", "$15&ndash;$24 / sq ft", "Pattern, two-tone color &amp; sealer"),
            ("Stamped pool deck (non-slip)", "$16&ndash;$25 / sq ft", "Slip additive included"),
            ("Stamped driveway", "$16&ndash;$26 / sq ft", "Thicker section, engineered joints"),
            ("Stamped border on plain field", "$8&ndash;$14 / linear ft", "Definition without full-field cost"),
            ("Stain / dye decorative finish", "+$3&ndash;$8 / sq ft", "Over new or sound existing slabs"),
            ("Re-seal &amp; color refresh", "$1.50&ndash;$3 / sq ft", "Existing stamped surfaces"),
            ("Slip-additive sealing", "$1.25&ndash;$2.50 / sq ft", "Wet-area grip without haze"),
        ],
        "faqs": [
            ("Does stamped concrete actually look like real stone?",
             "Good stamped work fools people at a garden party; bad stamped work announces itself from the street. The difference is layered color and honest texture depth. We color the slab integrally, antique it with a contrasting release, and press full-depth mats in a mapped layout &mdash; so the surface carries the tonal variation and shadow that real stone has. What stamped concrete never has is stone&rsquo;s joint lines moving independently, which is precisely why many owners prefer it: one continuous surface, no weeds, no settling pavers, no sand to wash out."),
            ("How does stamped concrete hold up in Florida sun and rain?",
             "The slab itself is as durable as any concrete we pour &mdash; the maintenance story lives entirely in the sealer. UV is the enemy of color: unsealed or over-aged sealer lets the sun bleach the release tones and chalk the surface. Plan on re-sealing every two to three years (a fast, inexpensive service we schedule with a reminder), keep the pressure washer at a respectful distance, and a stamped patio holds its depth for decades. We put the re-seal calendar in your care guide so it is a date, not a guess."),
            ("Is stamped concrete slippery around a pool?",
             "Sealed and additive-free, it can be &mdash; which is why we never leave it that way around water. Wet-area stamped work gets a fine polymer grit blended into the sealer coat: invisible at eye level, unmistakable underfoot. Combined with textured patterns (slate and shell carry more micro-relief than smooth ashlar), a properly sealed stamped deck grips comparably to broom finish. If your household runs to sprinting kids and wet feet, tell us &mdash; we&rsquo;ll bias pattern and grit accordingly."),
            ("Can you stamp over our existing patio or driveway?",
             "Not directly &mdash; stamping needs fresh, plastic concrete. But there are two honest routes to the look. If your slab is structurally sound, a <em>stamped overlay</em> adds a thin bonded layer we texture and color like new stamped work. If the slab is failing, we replace it and stamp the new pour &mdash; costlier, but the result starts its life on a correct base instead of inheriting an old slab&rsquo;s problems. The straightedge-and-crack inspection during your consultation tells us which route your surface qualifies for, and we quote what we find, not what sells."),
            ("What does stamped concrete cost versus pavers or natural stone?",
             "Installed in our market: stamped runs $15&ndash;$26 per square foot; comparable paver systems $14&ndash;$24; travertine and natural stone $22&ndash;$35. Stamped usually undercuts stone by a third to a half while carrying the pattern you actually wanted. The honest trade-offs: pavers repair invisibly section by section, stone carries the genuine article&rsquo;s prestige and temperature behavior, stamped gives you the seamless surface and the lowest maintenance floor. We install all three, so the comparison you get from us is math, not salesmanship."),
        ],
        "not_included": "Decorative work rides on the same rule as everything else: we do not overlay or stamp slabs with structural movement. Failing slabs get diagnosed and replaced honestly &mdash; never disguised.",
    },
    "concrete-slabs": {
        "name": "Concrete Slabs &amp; Pads",
        "slug": "concrete-slabs",
        "short": "Concrete Slabs",
        "h1_phrase": "Concrete Slabs &amp; Pads",
        "numeral": "05",
        "group": "Concrete",
        "answer_block": "Utility slabs and pads in the Orlando area run <strong>$8&ndash;$13 per square foot installed</strong> for standard 4-inch reinforced work, and <strong>$10&ndash;$16</strong> for thickened RV, boat, and equipment pads. Every pad is sized, sloped, and reinforced for the specific load it will carry &mdash; that&rsquo;s the whole craft.",
        "intro_lead": "Shed pads, AC and generator pads, RV and boat parking, garage aprons, and light commercial flatwork &mdash; each one engineered backward from the load it has to carry.",
        "craft_p1": "A slab is the most honest product in concrete: no pattern, no color, nowhere for shortcuts to hide except underground &mdash; which is exactly where they hide. The trade&rsquo;s quiet secret is that most &lsquo;cheap pad&rsquo; failures are engineering failures: a generator pad poured at sidewalk thickness, an RV pad without thickened edges, a shed base that ignored the water path across the yard. We design every pad backward from its duty. What will sit on it, how much does it weigh, how does it arrive (driven, rolled, craned?), and where does water want to go &mdash; those four answers set the thickness, reinforcement, base depth, and slope before we quote a number.",
        "craft_p2": "The range is wider than most homeowners expect. <strong>Equipment pads</strong> &mdash; AC condensers, pool heaters, standby generators &mdash; are small pours with strict flatness and elevation requirements (a generator warranty can hinge on its pad&rsquo;s level). <strong>Vehicle pads</strong> &mdash; RV, boat, trailer, third-car parking &mdash; carry point loads that demand five to six inches with thickened edges and real base depth. <strong>Building pads</strong> for sheds and studios need square, level, code-conscious layouts your building&rsquo;s installer will thank you for. And <strong>light commercial flatwork</strong> &mdash; dumpster pads, walk aprons, small-lot repairs for offices and HOAs &mdash; we handle with the same crew and the same written scope. If it is flat, load-bearing-lite, and outdoors, it is probably ours; if it is structural to a dwelling, it is honestly not, and we will say so.",
        "scope_items": [
            "Shed, studio &amp; outbuilding base pads",
            "AC condenser, pool-equipment &amp; generator pads",
            "RV, boat &amp; trailer parking pads (thickened)",
            "Third-car &amp; guest parking pads",
            "Garage aprons &amp; threshold transitions",
            "Basketball &amp; sport-court slabs",
            "Dumpster pads &amp; bollard bases (light commercial)",
            "HOA &amp; small-business flatwork repairs",
            "Subgrade probing &amp; lift-compacted rock base",
            "Thickened edges &amp; load-rated reinforcement",
            "Slope design for equipment drainage clearances",
            "Anchor-bolt &amp; tie-down coordination with installers",
        ],
        "options_rows": [
            ("4&Prime; utility pad", "Sheds, AC, garbage &amp; path pads", "The standard for static, light loads"),
            ("5&ndash;6&Prime; vehicle pad", "RVs, boats, trucks &amp; trailers", "Thickened edges, load-rated steel"),
            ("Generator pad", "Standby power systems", "Level-critical, spec&rsquo;d to the unit"),
            ("Sport slab", "Half-courts &amp; play pads", "Flatness-first finishing"),
        ],
        "pricing_rows": [
            ("Standard 4&Prime; reinforced pad", "$8&ndash;$13 / sq ft", "Shed, equipment &amp; utility duty"),
            ("Thickened vehicle pad (5&ndash;6&Prime;)", "$10&ndash;$16 / sq ft", "RV, boat &amp; trailer rated"),
            ("Generator / equipment pad", "$650&ndash;$1,900 each", "Sized &amp; leveled to the unit spec"),
            ("Shed / studio base pad", "$1,400&ndash;$4,500", "Typical 8&times;10 to 12&times;24 range"),
            ("Sport-court slab", "$9&ndash;$14 / sq ft", "Flatness-focused finish"),
            ("Garage apron replacement", "$900&ndash;$2,600", "Demo &amp; tie-in included"),
            ("Light commercial flatwork", "Quoted by scope", "Written proposal, insured crew"),
        ],
        "faqs": [
            ("How thick does my pad actually need to be?",
             "Match the slab to the load, not to a rule of thumb. Four inches of reinforced concrete over a compacted base carries sheds, AC units, and foot traffic all day. The moment wheels arrive &mdash; an RV, a boat trailer, a work truck &mdash; the math changes: point loads through tires demand five to six inches with thickened edges, and the base under it matters as much as the slab itself. Tell us the heaviest thing that will ever sit on the pad (be pessimistic), and we engineer to that. Upgrading thickness at pour time costs a little; discovering it was needed afterward costs the whole pad."),
            ("Can you pour a pad for my standby generator?",
             "Yes &mdash; and this is a pour where precision is the product. Generator manufacturers publish pad requirements: minimum dimensions, thickness, level tolerance, and clearances from the house and openings. Miss the level spec and some installers won&rsquo;t set the unit; miss the clearances and the inspection fails. We work from your unit&rsquo;s spec sheet, coordinate anchor placement with the installer, and pour a pad that passes the first time. Bring us the model number and the site &mdash; we handle the rest."),
            ("Does a shed or RV pad need a permit in Orange County?",
             "Frequently yes, and the rules differ by jurisdiction &mdash; Orange County, the Town of Windermere, Winter Garden, and the HOAs layered on top each have their own thresholds for accessory structures and paved additions. As part of the proposal we flag what your specific pad likely requires and prepare the site documentation. What we don&rsquo;t do is pour first and hope: an unpermitted pad can block a shed installation, an insurance claim, or a home sale years later. Twenty minutes of paperwork beats all of that."),
            ("Will a new pad mess up my yard&rsquo;s drainage?",
             "Only if it is designed carelessly &mdash; every square foot of concrete you add is a square foot of ground that stops absorbing rain. We slope pads to shed water toward the yard&rsquo;s existing drainage path, never toward the house or a neighbor, and on lots where the swale is already working hard we&rsquo;ll say so and adjust the design. In HOA communities this is doubly important: drainage complaints are one of the fastest routes to a violation letter, and pads that respect the lot&rsquo;s engineered flow simply never generate them."),
            ("Do you do commercial concrete work?",
             "Light commercial flatwork, yes: dumpster pads, walkway aprons, small parking pads, and repair work for offices, HOAs, churches, and storefronts across west Orlando. We are deliberately honest about scale &mdash; we are not a highway or tilt-wall outfit, and large structural work belongs with firms built for it. What we bring to small commercial scopes is the same thing homeowners get: a written proposal in one business day, full insurance documentation for your property manager, and a crew that shows up when the schedule says."),
        ],
        "not_included": "We do not pour dwelling foundations, structural building slabs, or anything requiring a state general-contractor license. Utility, vehicle, and light commercial flatwork is the honest boundary of this service.",
    },
    "concrete-repair-resurfacing": {
        "name": "Concrete Repair &amp; Resurfacing",
        "slug": "concrete-repair-resurfacing",
        "short": "Concrete Repair &amp; Resurfacing",
        "h1_phrase": "Concrete Repair &amp; Resurfacing",
        "numeral": "06",
        "group": "Concrete",
        "answer_block": "Concrete repair in west Orlando runs from <strong>$8&ndash;$22 per linear foot</strong> for crack routing and filling to <strong>$9&ndash;$16 per square foot</strong> for full decorative resurfacing. The honest first step is a diagnosis: surface damage can be repaired; base failure can&rsquo;t be patched, and we tell you which one you have.",
        "intro_lead": "Crack repair, spall restoration, decorative overlays, and removal-and-replacement &mdash; with a diagnosis first, so you fix the actual problem instead of repainting it.",
        "craft_p1": "Every repair estimate we run starts with the same question: is this slab&rsquo;s problem on the surface, or under it? <strong>Surface problems</strong> &mdash; scaling, spalling, stains, stable hairline cracks, a finish that&rsquo;s simply worn out &mdash; are genuinely repairable, and repairing them costs a fraction of replacement. <strong>Base problems</strong> &mdash; settlement, heaving, cracks that open and close with the seasons, panels tilting toward the house &mdash; live underground, and no overlay, filler, or paint fixes soil. The industry&rsquo;s dirty habit is selling surface treatments over base failures because the invoice is easier; a year later the same crack telegraphs through the beautiful new coating. Our first visit reads the crack pattern, checks panel movement, and tells you plainly which category you own &mdash; even when the honest answer is the more expensive one.",
        "craft_p2": "When the slab qualifies, the toolkit is deep. We rout and fill structural cracks with flexible polyurethane that moves with the slab instead of popping loose. We grind and patch spalled, flaking surfaces back to sound material. And for slabs that are structurally fine but visually finished, a <strong>decorative overlay</strong> &mdash; smooth, knock-down, or stamped &mdash; delivers a genuinely new surface: color, texture, and profile of your choosing over the slab you already own. When the slab doesn&rsquo;t qualify, we do the other honest thing: <strong>removal and replacement</strong>, priced with demolition and haul-away in the number, built back on a base engineered under the Craft Code. Repair when repair is real; replace when it isn&rsquo;t. That single sentence is this entire service.",
        "scope_items": [
            "On-site slab diagnosis &mdash; surface vs. base failure",
            "Crack routing &amp; flexible polyurethane filling",
            "Spall &amp; scaling repair, ground to sound material",
            "Decorative overlays: smooth, knock-down &amp; stamped",
            "Pool-deck acrylic resurfacing (cool-coat systems)",
            "Concrete removal &amp; full replacement",
            "Trip-hazard grinding at joints &amp; walk transitions",
            "Oil, rust &amp; tannin stain treatment",
            "Joint re-cutting &amp; re-caulking",
            "Color-matching repairs on decorative slabs",
            "Penetrating &amp; film-forming sealer application",
            "Pre-sale &amp; pre-listing concrete refresh packages",
        ],
        "options_rows": [
            ("Crack rout &amp; fill", "Stable cracks, moving joints", "Flexible fill that survives the seasons"),
            ("Spall / scaling repair", "Flaking, pitted surfaces", "Ground back to sound, patched flush"),
            ("Decorative overlay", "Sound slabs, tired finishes", "A new surface without demolition"),
            ("Remove &amp; replace", "Base failures, settled panels", "The honest fix when repair isn&rsquo;t"),
        ],
        "pricing_rows": [
            ("Crack routing &amp; filling", "$8&ndash;$22 / linear ft", "Flexible polyurethane systems"),
            ("Spall &amp; surface repair", "$6&ndash;$14 / sq ft", "Localized, ground &amp; patched"),
            ("Decorative overlay resurfacing", "$9&ndash;$16 / sq ft", "Smooth, textured, or stamped"),
            ("Pool-deck acrylic resurfacing", "$6&ndash;$10 / sq ft", "Cool-coat knock-down systems"),
            ("Trip-hazard grinding", "$150&ndash;$450 / location", "Walks, joints &amp; transitions"),
            ("Removal &amp; replacement", "$12&ndash;$17 / sq ft", "Demo &amp; haul-away included"),
            ("Stain treatment &amp; sealing", "$2&ndash;$5 / sq ft", "Oil, rust &amp; tannin protocols"),
        ],
        "faqs": [
            ("How do I know if my concrete can be repaired or needs replacement?",
             "Read what the slab is telling you. Flaking, pitting, staining, and thin cracks that stay the same width year-round are surface stories &mdash; repairable, resurfaceable, and worth doing. Cracks that open and close with the seasons, panels that have tilted or dropped, corners rocking underfoot, water pooling where it never used to &mdash; those are base stories, and treating them cosmetically buys one year, maybe two. Our estimate visit reads the pattern, probes the edges, and puts the verdict in writing with a price for the right fix. About a third of the repair calls we run end with us recommending the cheaper option than the caller expected; that&rsquo;s what diagnosis-first means."),
            ("Can you make a repair invisible?",
             "On plain gray concrete &mdash; close, but honestly never perfect: new material beside twenty-year-old material carries a tone difference that weathering slowly narrows. On decorative and colored slabs we get much nearer, layering color-matched patch systems and re-sealing the full panel so the repair reads as part of the surface. Where invisibility is the actual requirement &mdash; a front entry, a listing photo &mdash; the cleaner play is often overlaying the entire surface, which resets its whole face at once. We&rsquo;ll show you both numbers and let the mirror decide."),
            ("Is resurfacing just hiding problems?",
             "Over a failing slab &mdash; yes, and that is exactly why we refuse to do it there. Over a sound slab &mdash; no; it is a legitimate engineered system. Overlay products bond permanently to prepared concrete and carry their own wear surface, color, and texture; done correctly, a resurfaced patio or pool deck is a decade-plus solution at half the price of replacement. The integrity of the whole service rests on the qualifying inspection, which is why ours happens before the quote, with a straightedge, a chain drag, and no salesperson."),
            ("Our HOA flagged our stained, cracked driveway. Can you fix it quickly?",
             "This is one of our most common calls in the gated communities, and yes &mdash; the typical &lsquo;HOA letter&rsquo; scope (stain treatment, crack filling, a uniform re-seal) usually completes in one to two site days once scheduled. We photograph the finished surface for your compliance reply and, where the association requires it, provide the documentation of materials used. If the flagged driveway turns out to be past cosmetic help, we&rsquo;ll tell you that too, with the replacement quote attached &mdash; boards accept a scheduled replacement plan far more readily than a third round of patch-and-hope."),
            ("What does concrete repair cost in the Orlando area?",
             "Crack routing and filling: $8&ndash;$22 per linear foot. Localized spall repair: $6&ndash;$14 per square foot. Full decorative resurfacing: $9&ndash;$16 per square foot. Removal and replacement, when that&rsquo;s the honest answer: $12&ndash;$17 per square foot with demolition included. Most repair scopes on this page land between $600 and $4,000 total &mdash; and every one starts with the free diagnosis visit, so you spend on the fix, not on the guess."),
        ],
        "not_included": "We do not perform structural repairs to buildings, foundations, or load-bearing elements &mdash; slab flatwork, decks, drives, and walks are the honest limits of this service.",
    },
}
